/// A selectable record-start/stop cue voice. Every voice ships from an authentic
/// vintage synth — Yamaha DX7 (ROM1A/ROM1B) and Roland Juno-106 (KR-106 factory
/// presets); `SoundPackCatalog.swift` (generated by `scripts/generate-sounds.swift`)
/// supplies the full list. `id` doubles as the bundled cue stem: `<id>-start.m4a`
/// / `<id>-stop.m4a` under `Resources/Sounds/`. The `.none` pack plays nothing.
public struct SoundPack: Sendable, Hashable, Identifiable {
  public let id: String
  /// The voice's name, e.g. "ORCHESTRA" or "A11 Brass" — shown in the picker.
  public let label: String
  /// The picker section this voice belongs to, e.g. "Yamaha DX7 · ROM1A" or
  /// "Roland Juno-106 · A". nil for `.none`.
  public let group: String?

  /// The "no sound" choice.
  public static let none = SoundPack(id: "none", label: "None", group: nil)

  /// Bundled cue stem for the start cue, or nil when no sound plays.
  public var startFileName: String? { group == nil ? nil : "\(id)-start" }

  /// Bundled cue stem for the stop cue, or nil when no sound plays.
  public var stopFileName: String? { group == nil ? nil : "\(id)-stop" }

  /// The synth this voice comes from, for the ready-screen credit, e.g.
  /// "Yamaha DX-7". nil when no sound plays.
  public var synth: String? {
    guard let group else { return nil }
    if group.hasPrefix("Yamaha DX7") { return "Yamaha DX-7" }
    if group.hasPrefix("Roland Juno-106") { return "Roland Juno-106" }
    return nil
  }

  /// `.none` followed by the full catalog — the picker's complete option set.
  public static var all: [SoundPack] { [.none] + catalog }

  /// The default pack: ORCHESTRA (Yamaha DX7 ROM1A voice 6), falling back to
  /// `.none` only if the catalog is somehow empty.
  public static var defaultPack: SoundPack { catalog.first { $0.id == "rom1a-6" } ?? .none }

  /// Looks a pack up by its persisted `id`.
  public static func find(id: String) -> SoundPack? { all.first { $0.id == id } }

  /// Distinct group names, in catalog order — the picker's sections.
  public static var groups: [String] {
    var seen: [String] = []
    for pack in catalog {
      if let group = pack.group, !seen.contains(group) { seen.append(group) }
    }
    return seen
  }

  /// The voices belonging to one group, in catalog order.
  public static func voices(in group: String) -> [SoundPack] {
    catalog.filter { $0.group == group }
  }
}
