/// A selectable record-start/stop cue voice. Every voice ships from an authentic
/// vintage synth — Yamaha DX7 (ROM1A/ROM1B) and Roland Juno-106 (KR-106 factory
/// presets); `SoundPackCatalog.swift` (generated by `scripts/generate-sounds.swift`)
/// supplies the full list. `id` doubles as the bundled cue stem: `<id>-start.m4a`
/// / `<id>-stop.m4a` under `Resources/Sounds/`. The `.none` pack plays nothing.
public struct SoundPack: Sendable, Hashable, Identifiable {
  public let id: String
  /// The voice's name, e.g. "ORCHESTRA" or "A11 Brass" — shown in the picker.
  public let label: String
  /// The picker section this voice belongs to, e.g. "Yamaha DX7 · ROM1A" or
  /// "Roland Juno-106 · A". nil for `.none`.
  public let group: String?

  /// The "no sound" choice.
  public static let none = SoundPack(id: "none", label: "None", group: nil)

  /// True for the `.none` pack — the one voice with no bundled cues and no synth
  /// credit. A catalog entry always carries a `group` (its picker section), so its
  /// absence is what marks the silent pack. Internal: the app asks via
  /// `startFileName`/`stopFileName`, so exporting this would only trip
  /// periphery's redundant-public check.
  var isSilent: Bool { group == nil }

  /// Bundled cue stem for the start cue, or nil when no sound plays.
  public var startFileName: String? { isSilent ? nil : "\(id)-start" }

  /// Bundled cue stem for the stop cue, or nil when no sound plays.
  public var stopFileName: String? { isSilent ? nil : "\(id)-stop" }

  /// `.none` plus the full catalog, keyed by `id`. Private: the picker builds
  /// itself from `.none` + `groups` + `voices(in:)`, so this exists only to back
  /// `find(id:)`. Stored, not computed: `find` runs from a `Binding` getter on
  /// every settings render and from `CueSoundPlayer`'s pack load, and a computed
  /// version rebuilt a ~190-element array and scanned it linearly each time.
  private static let byID: [String: SoundPack] = {
    var index = [SoundPack.none.id: SoundPack.none]
    for pack in catalog {
      index[pack.id] = pack
    }
    return index
  }()

  /// The default pack: ORCHESTRA (Yamaha DX7 ROM1A voice 6), falling back to
  /// `.none` only if the catalog is somehow empty.
  ///
  /// Internal for the same reason as `isSilent` and `find(id:)`: the app reaches the
  /// default only through `fromPersisted` — restating it view-side is exactly what
  /// `SoundStepView` was corrected not to do — so exporting it would just trip
  /// periphery's redundant-public check.
  static let defaultPack: SoundPack = catalog.first { $0.id == "rom1a-6" } ?? .none

  /// Looks a pack up by its persisted `id`. Internal for the same reason as
  /// `isSilent`: the app reaches packs through `fromPersisted`, so exporting this
  /// would only trip periphery's redundant-public check.
  static func find(id: String) -> SoundPack? { byID[id] }

  /// Decodes a persisted pack id, falling back to `defaultPack` when the id is
  /// unset or names no known pack. The single decode-with-default rule shared by
  /// `SoundPackStore` and the `@AppStorage` views that read the raw id directly
  /// (so they re-render live on a Settings change) — mirroring
  /// `TriggerBinding.fromPersisted`.
  public static func fromPersisted(_ id: String?) -> SoundPack {
    guard let id, let pack = find(id: id) else { return .defaultPack }
    return pack
  }

  /// Distinct group names, in catalog order — the picker's sections. Dedupes
  /// through a `Set` (`insert(_:).inserted` as the filter, matching
  /// `KeyTermsStore.parse`) rather than an array `contains` scan per element.
  /// Stored for the same reason as `byID`: the picker reads it, then `voices(in:)`
  /// per group, on every settings render.
  public static let groups: [String] = {
    var seen = Set<String>()
    return catalog.compactMap { pack -> String? in
      guard let group = pack.group, seen.insert(group).inserted else { return nil }
      return group
    }
  }()

  /// The voices belonging to one group, in catalog order. Backed by a stored index
  /// so the picker's per-group read is a dictionary hit rather than a full-catalog
  /// filter per section.
  public static func voices(in group: String) -> [SoundPack] {
    voicesByGroup[group] ?? []
  }

  private static let voicesByGroup: [String: [SoundPack]] = {
    var index: [String: [SoundPack]] = [:]
    for pack in catalog {
      guard let group = pack.group else { continue }
      index[group, default: []].append(pack)
    }
    return index
  }()
}
