/// A selectable record-start/stop cue voice. Every voice ships from an authentic
/// vintage synth — Yamaha DX7 (ROM1A/ROM1B) and Roland Juno-106 (KR-106 factory
/// presets); `SoundPackCatalog.swift` (generated by `scripts/generate-sounds.swift`)
/// supplies the full list. `id` doubles as the bundled cue stem: `<id>-start.m4a`
/// / `<id>-stop.m4a` under `Resources/Sounds/`. The `.none` pack plays nothing.
public struct SoundPack: Sendable, Hashable, Identifiable {
  public let id: String
  /// The voice's name, e.g. "ORCHESTRA" or "A11 Brass" — shown in the picker.
  public let label: String
  /// The picker section this voice belongs to, e.g. "Yamaha DX7 · ROM1A" or
  /// "Roland Juno-106 · A". nil for `.none`.
  public let group: String?

  /// The "no sound" choice.
  public static let none = SoundPack(id: "none", label: "None", group: nil)

  /// True for the `.none` pack — the one voice with no bundled cues and no synth
  /// credit. A catalog entry always carries a `group` (its picker section), so its
  /// absence is what marks the silent pack. Internal: the app asks via
  /// `startFileName`/`stopFileName`, so exporting this would only trip
  /// periphery's redundant-public check.
  var isSilent: Bool { group == nil }

  /// Bundled cue stem for the start cue, or nil when no sound plays.
  public var startFileName: String? { isSilent ? nil : "\(id)-start" }

  /// Bundled cue stem for the stop cue, or nil when no sound plays.
  public var stopFileName: String? { isSilent ? nil : "\(id)-stop" }

  /// `.none` followed by the full catalog. Private: the picker builds itself from
  /// `.none` + `groups` + `voices(in:)`, so this exists only to back `find(id:)`.
  private static var all: [SoundPack] { [.none] + catalog }

  /// The default pack: ORCHESTRA (Yamaha DX7 ROM1A voice 6), falling back to
  /// `.none` only if the catalog is somehow empty.
  public static var defaultPack: SoundPack { catalog.first { $0.id == "rom1a-6" } ?? .none }

  /// Looks a pack up by its persisted `id`. Internal for the same reason as
  /// `isSilent`: the app reaches packs through `fromPersisted`, so exporting this
  /// would only trip periphery's redundant-public check.
  static func find(id: String) -> SoundPack? { all.first { $0.id == id } }

  /// Decodes a persisted pack id, falling back to `defaultPack` when the id is
  /// unset or names no known pack. The single decode-with-default rule shared by
  /// `SoundPackStore` and the `@AppStorage` views that read the raw id directly
  /// (so they re-render live on a Settings change) — mirroring
  /// `TriggerKey.fromPersisted`.
  public static func fromPersisted(_ id: String?) -> SoundPack {
    guard let id, let pack = find(id: id) else { return .defaultPack }
    return pack
  }

  /// Distinct group names, in catalog order — the picker's sections.
  public static var groups: [String] {
    var seen: [String] = []
    for pack in catalog {
      if let group = pack.group, !seen.contains(group) { seen.append(group) }
    }
    return seen
  }

  /// The voices belonging to one group, in catalog order.
  public static func voices(in group: String) -> [SoundPack] {
    catalog.filter { $0.group == group }
  }
}
