// Generated by scripts/design-tokens.swift from App/BlurtiOS/Design/tokens.json — do not edit.
// One line per variable (collection|name|type|value|alias|scopes|codeSyntax|use)
// and per gradient (GRADIENT|name|start|end|stops|use); core.js parses it.
// scripts/design-figma-call.sh puts it in front of core.js + foundations.js.
const TOKEN_LINES = `Brand|apple/dark-key|COLOR|#6B6B6B|||DesignTokens.Brand.appleDarkKey|the iPhone keyboard's dark key
Brand|apple/dark-modifier|COLOR|#464646|||DesignTokens.Brand.appleDarkModifier|the iPhone keyboard's dark modifier key
Brand|apple/dark-surface|COLOR|#2B2B2B|||DesignTokens.Brand.appleDarkSurface|the iPhone keyboard's dark surface
Brand|apple/light-modifier|COLOR|#ADB3BC|||DesignTokens.Brand.appleLightModifier|the iPhone keyboard's light modifier key
Brand|apple/light-surface|COLOR|#D1D5DB|||DesignTokens.Brand.appleLightSurface|the iPhone keyboard's light surface
Brand|black|COLOR|#000000|||DesignTokens.Brand.black|
Brand|card|COLOR|#EBE8E8|||DesignTokens.Brand.card|the warm card fill; the paper theme's surface
Brand|card-border|COLOR|#DEDBDB|||DesignTokens.Brand.cardBorder|the card's hairline; the paper theme's modifier key
Brand|cobolt|COLOR|#3923C7|||DesignTokens.Brand.cobolt|AssemblyAI's primary violet: the drop, never a key or a surface
Brand|green/100|COLOR|#CCE4D5|||DesignTokens.Brand.green100|the design system's UI-and-code green fill (unused on the phone yet)
Brand|green/200|COLOR|#99C8AC|||DesignTokens.Brand.green200|the design system's UI-and-code green highlight (unused on the phone yet)
Brand|green/400|COLOR|#67AD82|||DesignTokens.Brand.green400|the brand hue lifted for dark chrome: the meter, the ring, the wave on ink
Brand|green/700|COLOR|#01762F|||DesignTokens.Brand.green700|the wordmark green, light chrome (the app's accent in light)
Brand|green/mist|COLOR|#DBF5E6|||DesignTokens.Brand.greenMist|the pale green the orb lightens into
Brand|ink|COLOR|#1D1B16|||DesignTokens.Brand.ink|the brand ink: the Mac pill's body, the ink theme's surface
Brand|ink/600|COLOR|#3A362F|||DesignTokens.Brand.ink600|the Mac's dark card border
Brand|ink/700|COLOR|#33302A|||DesignTokens.Brand.ink700|an ordinary key on ink, one step up
Brand|ink/800|COLOR|#26231E|||DesignTokens.Brand.ink800|a modifier key on ink; the Mac's dark card fill
Brand|material/dark-key|COLOR|#575757|||DesignTokens.Brand.materialDarkKey|a key on the system's dark keyboard material (measured, iOS 27): the container case
Brand|material/dark-modifier|COLOR|#474747|||DesignTokens.Brand.materialDarkModifier|a modifier key on the system's dark material
Brand|material/dark-surface|COLOR|#373737|||DesignTokens.Brand.materialDarkSurface|the system's dark keyboard material (measured, iOS 27)
Brand|material/light-surface|COLOR|#E2E3E8|||DesignTokens.Brand.materialLightSurface|the system's light keyboard material (measured, iOS 27): what the gallery stands under a clear surface
Brand|neutral/300|COLOR|#D2D1D0|||DesignTokens.Brand.neutral300|black-100: the lightest warm grey
Brand|neutral/500|COLOR|#A5A4A2|||DesignTokens.Brand.neutral500|black-200: mono labels on the dark face
Brand|neutral/700|COLOR|#777673|||DesignTokens.Brand.neutral700|black-300: muted text and mono labels on the light face
Brand|neutral/900|COLOR|#4A4945|||DesignTokens.Brand.neutral900|black-400: body text on the light face
Brand|orange|COLOR|#E67F36|||DesignTokens.Brand.orange|the error word and ring, cancel, the Full Access note; never a red body
Brand|paper/200|COLOR|#ECEBE5|||DesignTokens.Brand.paper200|neutral-100: the light face's surface
Brand|paper/300|COLOR|#DAD7CB|||DesignTokens.Brand.paper300|neutral-200: a modifier key on the light face
Brand|paper/400|COLOR|#C7C3B2|||DesignTokens.Brand.paper400|neutral-300: hairlines and field borders on the light face
Brand|paper/page|COLOR|#FDFCF8|||DesignTokens.Brand.paperPage|the design system's page: the app's light ground
Brand|paper/tint|COLOR|#F5F3EB|||DesignTokens.Brand.paperTint|the warm off-white one step in: light cards, dark legends
Brand|violet/iris|COLOR|#887BDD|||DesignTokens.Brand.violetIris|the orb gradient's upper violet stop
Brand|violet/lavender|COLOR|#D7D3F4|||DesignTokens.Brand.violetLavender|the orb's lightest violet: its top and the gradient's ends
Brand|violet/periwinkle|COLOR|#B0A7E9|||DesignTokens.Brand.violetPeriwinkle|the orb's mid violet: the drop's halo
Brand|warm-white|COLOR|#F2EEE6|||DesignTokens.Brand.warmWhite|key legends on ink: warm white on warm ink
Brand|white|COLOR|#FFFFFF|||DesignTokens.Brand.white|
Themes|dark/container-key|COLOR|#575757|Brand:material/dark-key||DesignTokens.Themes.darkContainerKey|
Themes|dark/container-key-modifier|COLOR|#474747|Brand:material/dark-modifier||DesignTokens.Themes.darkContainerKeyModifier|
Themes|dark/field|COLOR|#33302A|Brand:ink/700||DesignTokens.Themes.darkField|
Themes|dark/field-border|COLOR|#3A362F|Brand:ink/600||DesignTokens.Themes.darkFieldBorder|
Themes|dark/key|COLOR|#33302A|Brand:ink/700||DesignTokens.Themes.darkKey|
Themes|dark/key-modifier|COLOR|#26231E|Brand:ink/800||DesignTokens.Themes.darkKeyModifier|
Themes|dark/legend|COLOR|#F5F3EB|Brand:paper/tint||DesignTokens.Themes.darkLegend|
Themes|dark/legend-secondary|COLOR|#A5A4A2|Brand:neutral/500||DesignTokens.Themes.darkLegendSecondary|
Themes|dark/material|COLOR|#373737|Brand:material/dark-surface||DesignTokens.Themes.darkMaterial|
Themes|dark/notice|COLOR|#E67F36|Brand:orange||DesignTokens.Themes.darkNotice|
Themes|dark/popup|COLOR|#33302A|Brand:ink/700||DesignTokens.Themes.darkPopup|
Themes|dark/signal|COLOR|#67AD82|Brand:green/400||DesignTokens.Themes.darkSignal|
Themes|dark/surface|COLOR|#1D1B16|Brand:ink||DesignTokens.Themes.darkSurface|
Themes|light/container-key|COLOR|#FFFFFF|Brand:white||DesignTokens.Themes.lightContainerKey|
Themes|light/container-key-modifier|COLOR|#DAD7CB|Brand:paper/300||DesignTokens.Themes.lightContainerKeyModifier|
Themes|light/field|COLOR|#FFFFFF|Brand:white||DesignTokens.Themes.lightField|
Themes|light/field-border|COLOR|#C7C3B2|Brand:paper/400||DesignTokens.Themes.lightFieldBorder|
Themes|light/key|COLOR|#FFFFFF|Brand:white||DesignTokens.Themes.lightKey|
Themes|light/key-modifier|COLOR|#DAD7CB|Brand:paper/300||DesignTokens.Themes.lightKeyModifier|
Themes|light/legend|COLOR|#1D1B16|Brand:ink||DesignTokens.Themes.lightLegend|
Themes|light/legend-secondary|COLOR|#777673|Brand:neutral/700||DesignTokens.Themes.lightLegendSecondary|
Themes|light/material|COLOR|#E2E3E8|Brand:material/light-surface||DesignTokens.Themes.lightMaterial|
Themes|light/notice|COLOR|#E67F36|Brand:orange||DesignTokens.Themes.lightNotice|
Themes|light/popup|COLOR|#FFFFFF|Brand:white||DesignTokens.Themes.lightPopup|
Themes|light/signal|COLOR|#01762F|Brand:green/700||DesignTokens.Themes.lightSignal|
Themes|light/surface|COLOR|#ECEBE5|Brand:paper/200||DesignTokens.Themes.lightSurface|
Keyboard|app/accent-dark|COLOR|#67AD82|Brand:green/400|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appAccentDark|the catalog's AccentColor in dark
Keyboard|app/accent-light|COLOR|#01762F|Brand:green/700|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appAccentLight|the catalog's AccentColor in light
Keyboard|app/card-border-dark|COLOR|#3A362F|Brand:ink/600|STROKE_COLOR|DesignTokens.Keyboard.appCardBorderDark|the catalog's CardBorder in dark
Keyboard|app/card-border-light|COLOR|#C7C3B2|Brand:paper/400|STROKE_COLOR|DesignTokens.Keyboard.appCardBorderLight|the catalog's CardBorder in light
Keyboard|app/card-fill-dark|COLOR|#26231E|Brand:ink/800|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appCardFillDark|the catalog's CardFill in dark
Keyboard|app/card-fill-light|COLOR|#F5F3EB|Brand:paper/tint|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appCardFillLight|the catalog's CardFill in light
Keyboard|app/cta-dark|COLOR|#67AD82|Brand:green/400|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appCtaDark|the catalog's CTA in dark: the site's button green
Keyboard|app/cta-light|COLOR|#01762F|Brand:green/700|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appCtaLight|the catalog's CTA in light: the one green button
Keyboard|app/cta-text-dark|COLOR|#1D1B16|Brand:ink|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appCtaTextDark|the catalog's CTAText in dark: ink on green, as the site
Keyboard|app/cta-text-light|COLOR|#FFFFFF|Brand:white|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appCtaTextLight|the catalog's CTAText in light
Keyboard|app/muted-dark|COLOR|#A5A4A2|Brand:neutral/500|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appMutedDark|the catalog's Muted in dark
Keyboard|app/muted-light|COLOR|#777673|Brand:neutral/700|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appMutedLight|the catalog's Muted in light: eyebrows, captions, secondary text
Keyboard|app/page-dark|COLOR|#1D1B16|Brand:ink|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appPageDark|the catalog's Page in dark: ink, the website's ground
Keyboard|app/page-light|COLOR|#FDFCF8|Brand:paper/page|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appPageLight|the catalog's Page in light: the design system's page
Keyboard|app/text-dark|COLOR|#F5F3EB|Brand:paper/tint|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appTextDark|the catalog's Text in dark
Keyboard|app/text-light|COLOR|#1D1B16|Brand:ink|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appTextLight|the catalog's Text in light
Keyboard|kb/cancel|COLOR|#E67F36|Brand:orange|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.kbCancel|the panel's cancel ×
Keyboard|kb/field|COLOR|#33302A|Themes:dark/field|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.kbField|the key-term field
Keyboard|kb/field-border|COLOR|#3A362F|Themes:dark/field-border|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.kbFieldBorder|the field's hairline
Keyboard|kb/full-access-note|COLOR|#E67F36|Brand:orange|TEXT_FILL|DesignTokens.Keyboard.kbFullAccessNote|the one line of words the keyboard ever shows
Keyboard|kb/key|COLOR|#33302A|Themes:dark/key|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.kbKey|an ordinary key
Keyboard|kb/key-modifier|COLOR|#26231E|Themes:dark/key-modifier|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.kbKeyModifier|shift, delete, globe, return, 123, cancel
Keyboard|kb/legend|COLOR|#F5F3EB|Themes:dark/legend|TEXT_FILL|DesignTokens.Keyboard.kbLegend|key legends and bare glyphs
Keyboard|kb/legend-secondary|COLOR|#A5A4A2|Themes:dark/legend-secondary|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.kbLegendSecondary|the mono word labels (123, ABC, return, space) and the + at rest
Keyboard|kb/notice-error|COLOR|#E67F36|Brand:orange|STROKE_COLOR|DesignTokens.Keyboard.kbNoticeError|the solid ring and glyph for an error
Keyboard|kb/popup|COLOR|#33302A|Themes:dark/popup|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.kbPopup|the letter pop-up
Keyboard|kb/signal|COLOR|#67AD82|Themes:dark/signal|SHAPE_FILL,TEXT_FILL|DesignTokens.Keyboard.kbSignal|the wave, the caret, the saved check
Keyboard|kb/surface|COLOR|#1D1B16|Themes:dark/surface|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.kbSurface|the design face's surface (Figma binds to kb/*; Swift reads the palette)
Metrics|addterm/chip-gap|FLOAT|6||GAP|DesignTokens.Metrics.addtermChipGap|between the chip's glyph and the word
Metrics|addterm/chip-max-width|FLOAT|240||WIDTH_HEIGHT|DesignTokens.Metrics.addtermChipMaxWidth|the most the chip may take in the panel's corner, clear of the cancel ×
Metrics|addterm/chip-min-width|FLOAT|96||WIDTH_HEIGHT|DesignTokens.Metrics.addtermChipMinWidth|the room the voice bar keeps for the chip; the element gives way beyond it
Metrics|addterm/chip-pad|FLOAT|10||WIDTH_HEIGHT|DesignTokens.Metrics.addtermChipPad|the selected-word chip's side padding
Metrics|addterm/inset|FLOAT|6||GAP|DesignTokens.Metrics.addtermInset|the + from the panel's corner
Metrics|app/button-height|FLOAT|40||WIDTH_HEIGHT|DesignTokens.Metrics.appButtonHeight|the brand's button
Metrics|app/button-pad|FLOAT|12||WIDTH_HEIGHT|DesignTokens.Metrics.appButtonPad|its side padding
Metrics|app/card-pad|FLOAT|16||WIDTH_HEIGHT|DesignTokens.Metrics.appCardPad|inside a card
Metrics|app/chip-gap|FLOAT|8||GAP|DesignTokens.Metrics.appChipGap|between chips
Metrics|app/chip-pad-x|FLOAT|12||WIDTH_HEIGHT|DesignTokens.Metrics.appChipPadX|a style chip's side padding
Metrics|app/chip-pad-y|FLOAT|8||WIDTH_HEIGHT|DesignTokens.Metrics.appChipPadY|and its top and bottom
Metrics|app/header-height|FLOAT|44||WIDTH_HEIGHT|DesignTokens.Metrics.appHeaderHeight|the home header: wordmark and gear
Metrics|app/hero-gap|FLOAT|14||GAP|DesignTokens.Metrics.appHeroGap|between the hero's pieces
Metrics|app/hero-pad|FLOAT|20||WIDTH_HEIGHT|DesignTokens.Metrics.appHeroPad|inside the hero card
Metrics|app/icon|FLOAT|20||WIDTH_HEIGHT|DesignTokens.Metrics.appIcon|the header's gear, the copy glyph
Metrics|app/line-gap|FLOAT|6||GAP|DesignTokens.Metrics.appLineGap|between lines of one thought
Metrics|app/page-pad|FLOAT|20||WIDTH_HEIGHT|DesignTokens.Metrics.appPagePad|the screens' side padding
Metrics|app/preview-gap|FLOAT|8||GAP|DesignTokens.Metrics.appPreviewGap|between the theme card's two faces
Metrics|app/section-gap|FLOAT|24||GAP|DesignTokens.Metrics.appSectionGap|between the home screen's sections
Metrics|app/setup-number-width|FLOAT|24||WIDTH_HEIGHT|DesignTokens.Metrics.appSetupNumberWidth|the setup steps' mono numerals
Metrics|app/stack-gap|FLOAT|12||GAP|DesignTokens.Metrics.appStackGap|between a section's eyebrow and its content, and between cards
Metrics|card/border|FLOAT|1||STROKE_FLOAT,WIDTH_HEIGHT|DesignTokens.Metrics.cardBorder|the card's hairline
Metrics|card/radius|FLOAT|12||CORNER_RADIUS|DesignTokens.Metrics.cardRadius|the app's cards (radius/card)
Metrics|caret/height|FLOAT|20||WIDTH_HEIGHT|DesignTokens.Metrics.caretHeight|
Metrics|caret/lead|FLOAT|1||GAP|DesignTokens.Metrics.caretLead|the caret's gap from the text
Metrics|caret/radius|FLOAT|1||CORNER_RADIUS|DesignTokens.Metrics.caretRadius|
Metrics|caret/width|FLOAT|2||STROKE_FLOAT,WIDTH_HEIGHT|DesignTokens.Metrics.caretWidth|
Metrics|glyph/hit|FLOAT|32||WIDTH_HEIGHT|DesignTokens.Metrics.glyphHit|the +, × and ✓ touch targets
Metrics|grille/bar-height|FLOAT|28||WIDTH_HEIGHT|DesignTokens.Metrics.grilleBarHeight|
Metrics|grille/bar-width|FLOAT|64||WIDTH_HEIGHT|DesignTokens.Metrics.grilleBarWidth|the grille in the voice bar
Metrics|grille/dot|FLOAT|2||WIDTH_HEIGHT|DesignTokens.Metrics.grilleDot|a dot's diameter
Metrics|grille/glint-arm|FLOAT|1.6||WIDTH_HEIGHT|DesignTokens.Metrics.grilleGlintArm|the cross glint's vertical arm, as a fraction of the grille's height
Metrics|grille/glint-width|FLOAT|1||WIDTH_HEIGHT|DesignTokens.Metrics.grilleGlintWidth|the glint's arms
Metrics|grille/home-height|FLOAT|108||WIDTH_HEIGHT|DesignTokens.Metrics.grilleHomeHeight|
Metrics|grille/home-width|FLOAT|240||WIDTH_HEIGHT|DesignTokens.Metrics.grilleHomeWidth|the grille on the home screen
Metrics|grille/panel-height|FLOAT|72||WIDTH_HEIGHT|DesignTokens.Metrics.grillePanelHeight|
Metrics|grille/panel-width|FLOAT|160||WIDTH_HEIGHT|DesignTokens.Metrics.grillePanelWidth|the grille in the panel
Metrics|grille/pitch|FLOAT|4||WIDTH_HEIGHT|DesignTokens.Metrics.grillePitch|the dot lattice: one dot every
Metrics|grille/sheen-width|FLOAT|0.35||WIDTH_HEIGHT|DesignTokens.Metrics.grilleSheenWidth|the sheen's band, as a fraction of the width
Metrics|key/abc-width-402|FLOAT|43.333||WIDTH_HEIGHT|DesignTokens.Metrics.keyAbcWidth402|123 and the globe at 402 pt: the iPhone's
Metrics|key/gap|FLOAT|6||GAP|DesignTokens.Metrics.keyGap|between keys, the iPhone's
Metrics|key/height|FLOAT|43||WIDTH_HEIGHT|DesignTokens.Metrics.keyHeight|every key: the iPhone's cap height (apple-geometry.json)
Metrics|key/letter-width-402|FLOAT|33.5||WIDTH_HEIGHT|DesignTokens.Metrics.keyLetterWidth402|a letter key at 402 pt: (width − 2 × margin/side − 9 × key/gap) / 10
Metrics|key/min-width|FLOAT|43.333||WIDTH_HEIGHT|DesignTokens.Metrics.keyMinWidth|a key that isn't given a width: the iPhone's 123 key at 402 pt
Metrics|key/pad|FLOAT|4||GAP|DesignTokens.Metrics.keyPad|a legend's side padding on a min-width key
Metrics|key/radius|FLOAT|8||CORNER_RADIUS|DesignTokens.Metrics.keyRadius|flat keys, one colour at this corner: the iPhone's (fitted 8.17)
Metrics|key/reference-width|FLOAT|402||WIDTH_HEIGHT|DesignTokens.Metrics.keyReferenceWidth|the width the @402 tokens were measured at (iPhone 18 Pro); widths scale from it
Metrics|key/return-width-402|FLOAT|92.667||WIDTH_HEIGHT|DesignTokens.Metrics.keyReturnWidth402|return at 402 pt: two 123 keys and a gap
Metrics|key/side-gap|FLOAT|13.667||GAP|DesignTokens.Metrics.keySideGap|shift and delete stand this far from the letters: the iPhone's
Metrics|key/side-width-402|FLOAT|45.583||WIDTH_HEIGHT|DesignTokens.Metrics.keySideWidth402|shift and delete at 402 pt: what seven letters and the side gaps leave, halved (measured 45.5)
Metrics|key/space-width-402|FLOAT|191.667||WIDTH_HEIGHT|DesignTokens.Metrics.keySpaceWidth402|space at 402 pt beside 123, the globe and return: what is left (measured 191.333)
Metrics|layout/full|FLOAT|270||WIDTH_HEIGHT|DesignTokens.Metrics.layoutFull|margin/vertical + voicebar/height + 4 × key/height + 3 × row/gap + margin/bottom-keys
Metrics|layout/panel|FLOAT|216||WIDTH_HEIGHT|DesignTokens.Metrics.layoutPanel|chosen: room for the 96 orb over one key row
Metrics|layout/slim|FLOAT|60||WIDTH_HEIGHT|DesignTokens.Metrics.layoutSlim|2 × margin/vertical + voicebar/height
Metrics|margin/bottom-keys|FLOAT|13||WIDTH_HEIGHT|DesignTokens.Metrics.marginBottomKeys|under a bottom row of keys (the full keyboard, the panel): the iPhone's
Metrics|margin/side|FLOAT|6.5||WIDTH_HEIGHT|DesignTokens.Metrics.marginSide|at the keyboard's sides: the iPhone's cap margin, (402 − 10 letters − 9 gaps) / 2
Metrics|margin/vertical|FLOAT|8||WIDTH_HEIGHT|DesignTokens.Metrics.marginVertical|the keyboard's top, and the slim bar's bottom
Metrics|opacity/disabled|FLOAT|0.4||OPACITY|DesignTokens.Metrics.opacityDisabled|the + without Full Access
Metrics|opacity/glint|FLOAT|0.95||OPACITY|DesignTokens.Metrics.opacityGlint|the cross glint when the words land
Metrics|opacity/grain-dark|FLOAT|0.14||OPACITY|DesignTokens.Metrics.opacityGrainDark|film grain over the dark face: matte, the brand's texture
Metrics|opacity/grain-light|FLOAT|0.08||OPACITY|DesignTokens.Metrics.opacityGrainLight|film grain over the light face: paper, lighter
Metrics|opacity/grille-rest|FLOAT|0.55||OPACITY|DesignTokens.Metrics.opacityGrilleRest|the dots at rest, over the key colour
Metrics|opacity/hairline|FLOAT|0.5||OPACITY|DesignTokens.Metrics.opacityHairline|
Metrics|opacity/legend|FLOAT|1||OPACITY|DesignTokens.Metrics.opacityLegend|key legends over the cap; below 1 they sit back
Metrics|opacity/legend-muted|FLOAT|0.5||OPACITY|DesignTokens.Metrics.opacityLegendMuted|the + at rest
Metrics|opacity/off|FLOAT|0.6||OPACITY|DesignTokens.Metrics.opacityOff|the element when Blurt isn't ready — dim and still, but there: a tap opens the app
Metrics|opacity/placeholder|FLOAT|0.4||OPACITY|DesignTokens.Metrics.opacityPlaceholder|the field's placeholder
Metrics|opacity/popup-shadow|FLOAT|0.12||OPACITY|DesignTokens.Metrics.opacityPopupShadow|
Metrics|opacity/press-brighten|FLOAT|0.15||OPACITY|DesignTokens.Metrics.opacityPressBrighten|a key lightens this much while pressed
Metrics|opacity/pressed|FLOAT|0.85||OPACITY|DesignTokens.Metrics.opacityPressed|a brand button while pressed: a colour change, no lift
Metrics|opacity/sheen|FLOAT|0.22||OPACITY|DesignTokens.Metrics.opacitySheen|the light passing over the element at rest: chrome catching light
Metrics|opacity/surface-vignette|FLOAT|0||OPACITY|DesignTokens.Metrics.opacitySurfaceVignette|a soft darkening toward the surface's edges; 0 is none
Metrics|opacity/term-cancel|FLOAT|0.7||OPACITY|DesignTokens.Metrics.opacityTermCancel|the field's ×
Metrics|panel/spacing|FLOAT|12||GAP|DesignTokens.Metrics.panelSpacing|between the panel's orb and its key row
Metrics|picker/preview-width|FLOAT|393||WIDTH_HEIGHT|DesignTokens.Metrics.pickerPreviewWidth|the theme card draws the keyboard at this width
Metrics|picker/radius|FLOAT|10||CORNER_RADIUS|DesignTokens.Metrics.pickerRadius|the theme card's preview corners
Metrics|picker/scale|FLOAT|0.42|||DesignTokens.Metrics.pickerScale|then scales it to fit two across
Metrics|popup/extra-width|FLOAT|18||WIDTH_HEIGHT|DesignTokens.Metrics.popupExtraWidth|the letter pop-up is the key width plus this
Metrics|popup/height|FLOAT|56||WIDTH_HEIGHT|DesignTokens.Metrics.popupHeight|
Metrics|popup/offset|FLOAT|58||WIDTH_HEIGHT|DesignTokens.Metrics.popupOffset|the pop-up sits this far above the key
Metrics|popup/radius|FLOAT|10||CORNER_RADIUS|DesignTokens.Metrics.popupRadius|
Metrics|popup/shadow-radius|FLOAT|8||WIDTH_HEIGHT|DesignTokens.Metrics.popupShadowRadius|the one thing that floats
Metrics|popup/shadow-y|FLOAT|2||WIDTH_HEIGHT|DesignTokens.Metrics.popupShadowY|
Metrics|radius/button|FLOAT|4||WIDTH_HEIGHT|DesignTokens.Metrics.radiusButton|the brand's buttons and the grille: rectangular, never a pill
Metrics|radius/card|FLOAT|12||WIDTH_HEIGHT|DesignTokens.Metrics.radiusCard|the brand's cards
Metrics|radius/hero|FLOAT|16||WIDTH_HEIGHT|DesignTokens.Metrics.radiusHero|the brand's featured cards
Metrics|radius/input|FLOAT|8||WIDTH_HEIGHT|DesignTokens.Metrics.radiusInput|the brand's inputs: the key-term field
Metrics|ribs/rest-height|FLOAT|16||WIDTH_HEIGHT|DesignTokens.Metrics.ribsRestHeight|
Metrics|ribs/rest-width|FLOAT|40||WIDTH_HEIGHT|DesignTokens.Metrics.ribsRestWidth|the ribs asleep: the wave's own bars at rest
Metrics|row/gap|FLOAT|11||GAP|DesignTokens.Metrics.rowGap|between rows, the iPhone's
Metrics|slim/spacing|FLOAT|8||GAP|DesignTokens.Metrics.slimSpacing|between the slim bar's keys
Metrics|streak/arm|FLOAT|1.4||WIDTH_HEIGHT|DesignTokens.Metrics.streakArm|the landing flash's vertical arm, as a fraction of the box's height
Metrics|streak/height|FLOAT|2||WIDTH_HEIGHT|DesignTokens.Metrics.streakHeight|the light streak while recording
Metrics|streak/line|FLOAT|1||WIDTH_HEIGHT|DesignTokens.Metrics.streakLine|the hairline at rest
Metrics|streak/point|FLOAT|4||WIDTH_HEIGHT|DesignTokens.Metrics.streakPoint|the bright point at the centre
Metrics|surface/paint|FLOAT|0||WIDTH_HEIGHT|DesignTokens.Metrics.surfacePaint|1 paints the face's surface under the keys; 0 leaves it clear, so the host's own keyboard material (iOS 26's rounded container, which insets a third-party keyboard and cannot be painted over) is the surface, seamlessly, and the keys take the container colours
Metrics|surface/vignette-end|FLOAT|0.75||WIDTH_HEIGHT|DesignTokens.Metrics.surfaceVignetteEnd|where it is full
Metrics|surface/vignette-start|FLOAT|0.3||WIDTH_HEIGHT|DesignTokens.Metrics.surfaceVignetteStart|where the vignette begins, as a fraction of the keyboard's width
Metrics|term/border|FLOAT|1||WIDTH_HEIGHT|DesignTokens.Metrics.termBorder|the field's hairline
Metrics|term/gap|FLOAT|8||GAP|DesignTokens.Metrics.termGap|× · field · ✓
Metrics|term/height|FLOAT|36||WIDTH_HEIGHT|DesignTokens.Metrics.termHeight|the key-term field's capsule
Metrics|term/inset|FLOAT|2||GAP|DesignTokens.Metrics.termInset|the field row's side inset
Metrics|term/pad|FLOAT|14||GAP|DesignTokens.Metrics.termPad|the field's side padding
Metrics|term/radius|FLOAT|8||CORNER_RADIUS|DesignTokens.Metrics.termRadius|the key-term field: the brand's input corners (radius/input)
Metrics|voice/bar-height|FLOAT|32||WIDTH_HEIGHT|DesignTokens.Metrics.voiceBarHeight|
Metrics|voice/bar-width|FLOAT|160||WIDTH_HEIGHT|DesignTokens.Metrics.voiceBarWidth|the voice element's box in the voice bar — the most it takes (the ribs awake, the streak); the + sits beside what shows
Metrics|voice/home-height|FLOAT|112||WIDTH_HEIGHT|DesignTokens.Metrics.voiceHomeHeight|
Metrics|voice/home-width|FLOAT|280||WIDTH_HEIGHT|DesignTokens.Metrics.voiceHomeWidth|the box on the home screen
Metrics|voice/panel-height|FLOAT|88||WIDTH_HEIGHT|DesignTokens.Metrics.voicePanelHeight|
Metrics|voice/panel-width|FLOAT|300||WIDTH_HEIGHT|DesignTokens.Metrics.voicePanelWidth|the box in the panel
Metrics|voice/press-scale|FLOAT|0.94||WIDTH_HEIGHT|DesignTokens.Metrics.voicePressScale|the element while pressed
Metrics|voicebar/addterm-clearance|FLOAT|12||GAP|DesignTokens.Metrics.voicebarAddtermClearance|between the element and the +
Metrics|voicebar/height|FLOAT|44||WIDTH_HEIGHT|DesignTokens.Metrics.voicebarHeight|the voice row, where the system puts its suggestion bar
Metrics|voicebar/note-gap|FLOAT|10||GAP|DesignTokens.Metrics.voicebarNoteGap|between the orb and the Full Access note
Metrics|wave/bar|FLOAT|2||STROKE_FLOAT,WIDTH_HEIGHT|DesignTokens.Metrics.waveBar|a wave bar's width
Metrics|wave/bar-height|FLOAT|24||WIDTH_HEIGHT|DesignTokens.Metrics.waveBarHeight|
Metrics|wave/gap|FLOAT|2||GAP|DesignTokens.Metrics.waveGap|between wave bars
Metrics|wave/home-height|FLOAT|44||WIDTH_HEIGHT|DesignTokens.Metrics.waveHomeHeight|
Metrics|wave/panel-height|FLOAT|40||WIDTH_HEIGHT|DesignTokens.Metrics.wavePanelHeight|
Metrics|wordmark/height|FLOAT|22||WIDTH_HEIGHT|DesignTokens.Metrics.wordmarkHeight|
Typography|ratio/voice-glyph|FLOAT|0.34|||DesignTokens.Typography.ratioVoiceGlyph|the clipboard and exclamation glyphs, as a fraction of the voice element's height
Typography|size/body|FLOAT|16||FONT_SIZE|DesignTokens.Typography.sizeBody|the app's body text
Typography|size/caption|FLOAT|14||FONT_SIZE|DesignTokens.Typography.sizeCaption|the app's small text
Typography|size/cta|FLOAT|14||FONT_SIZE|DesignTokens.Typography.sizeCta|a mono button label in the app (E2)
Typography|size/eyebrow|FLOAT|12||FONT_SIZE|DesignTokens.Typography.sizeEyebrow|a mono eyebrow in the app (E1)
Typography|size/glyph|FLOAT|17||FONT_SIZE|DesignTokens.Typography.sizeGlyph|the +, × and ✓
Typography|size/label|FLOAT|12||FONT_SIZE|DesignTokens.Typography.sizeLabel|the mono word labels on keys: 123, ABC, #+=, space, the return label
Typography|size/legend|FLOAT|16||FONT_SIZE|DesignTokens.Typography.sizeLegend|every other key
Typography|size/letter|FLOAT|24||FONT_SIZE|DesignTokens.Typography.sizeLetter|letter keys: the iPhone's (estimated from the l glyph, apple-geometry.json)
Typography|size/popup|FLOAT|32||FONT_SIZE|DesignTokens.Typography.sizePopup|the letter pop-up
Typography|size/term|FLOAT|17||FONT_SIZE|DesignTokens.Typography.sizeTerm|the key-term field
Typography|size/title|FLOAT|34||FONT_SIZE|DesignTokens.Typography.sizeTitle|the app's serif headline
Typography|tracking/cta|FLOAT|1.4||LETTER_SPACING|DesignTokens.Typography.trackingCta|uppercase mono at 14: the brand's E2 tracking
Typography|tracking/eyebrow|FLOAT|1.2||LETTER_SPACING|DesignTokens.Typography.trackingEyebrow|uppercase mono at 12: the brand's E1 tracking
Typography|weight/glyph|STRING|medium||FONT_STYLE|DesignTokens.Typography.weightGlyph|
Typography|weight/label|STRING|medium||FONT_STYLE|DesignTokens.Typography.weightLabel|
Typography|weight/legend|STRING|medium||FONT_STYLE|DesignTokens.Typography.weightLegend|
Typography|weight/letter|STRING|regular||FONT_STYLE|DesignTokens.Typography.weightLetter|
Typography|weight/popup|STRING|regular||FONT_STYLE|DesignTokens.Typography.weightPopup|
Typography|weight/term|STRING|regular||FONT_STYLE|DesignTokens.Typography.weightTerm|
Typography|weight/voice-glyph|STRING|semibold||FONT_STYLE|DesignTokens.Typography.weightVoiceGlyph|
Motion|caret|FLOAT|0.5|||DesignTokens.Motion.caret|the caret's blink
Motion|chip-hold|FLOAT|0.4|||DesignTokens.Motion.chipHold|holding the chip opens the field instead of adding
Motion|colour|FLOAT|0.2|||DesignTokens.Motion.colour|a colour or fill changing state: the brand's transition
Motion|ease/signature|STRING|0.22,1,0.36,1|||DesignTokens.Motion.easeSignature|the house curve for everything that moves; nothing springs
Motion|flip|FLOAT|0.25|||DesignTokens.Motion.flip|the panel's carousel
Motion|glint-life|FLOAT|0.5|||DesignTokens.Motion.glintLife|a facet's flash while recording
Motion|height-change|FLOAT|0.25|||DesignTokens.Motion.heightChange|the keyboard resizing
Motion|key-press|FLOAT|0.08|||DesignTokens.Motion.keyPress|a key lighting
Motion|landing|FLOAT|0.6|||DesignTokens.Motion.landing|the glint when the words land
Motion|press|FLOAT|0.1|||DesignTokens.Motion.press|the orb's press; the one thing that answers at once
Motion|ring-period|FLOAT|1.6|||DesignTokens.Motion.ringPeriod|one turn of the ring, the Mac's cadence
Motion|sheen|FLOAT|4|||DesignTokens.Motion.sheen|one pass of the light over the element at rest
Motion|sheen-working|FLOAT|1.6|||DesignTokens.Motion.sheenWorking|and while something is happening: the ring's cadence
Motion|state-fade|FLOAT|0.5|||DesignTokens.Motion.stateFade|every other change on the key: the ring, a glyph, the dimming
Motion|term-swap|FLOAT|0.4|||DesignTokens.Motion.termSwap|the voice bar becoming the field
Motion|wave-fade|FLOAT|0.7|||DesignTokens.Motion.waveFade|the orb and the wave crossing, either way
Fonts|body/bold|STRING|UN-11ST-Bold|||DesignTokens.Fonts.bodyBold|
Fonts|body/family|STRING|UN-11 ST||FONT_FAMILY|DesignTokens.Fonts.bodyFamily|the app's body text
Fonts|body/regular|STRING|UN-11ST-Regular|||DesignTokens.Fonts.bodyRegular|
Fonts|heading/family|STRING|Oceanic Text||FONT_FAMILY|DesignTokens.Fonts.headingFamily|the app's serif headlines, sentence case, tight
Fonts|heading/regular|STRING|OceanicText-Regular|||DesignTokens.Fonts.headingRegular|
Fonts|mono/family|STRING|Modern Gothic Mono||FONT_FAMILY|DesignTokens.Fonts.monoFamily|eyebrows, CTAs, the keyboard's word labels
Fonts|mono/light|STRING|ModernGothicMono-Light|||DesignTokens.Fonts.monoLight|
Fonts|mono/medium|STRING|ModernGothicMono-Medium|||DesignTokens.Fonts.monoMedium|
Fonts|mono/regular|STRING|ModernGothicMono-Regular|||DesignTokens.Fonts.monoRegular|`;
const GROUPS = ["Brand", "Themes", "Keyboard", "Metrics", "Typography", "Motion", "Fonts"];
