// Generated by scripts/design-tokens.swift from App/BlurtiOS/Design/tokens.json — do not edit.
// One line per variable (collection|name|type|value|alias|scopes|codeSyntax|use)
// and per gradient (GRADIENT|name|start|end|stops|use); core.js parses it.
// scripts/design-figma-call.sh puts it in front of core.js + foundations.js.
const TOKEN_LINES = `Brand|apple/dark-key|COLOR|#6B6B6B|||DesignTokens.Brand.appleDarkKey|the iPhone keyboard's dark key
Brand|apple/dark-modifier|COLOR|#464646|||DesignTokens.Brand.appleDarkModifier|the iPhone keyboard's dark modifier key
Brand|apple/dark-surface|COLOR|#2B2B2B|||DesignTokens.Brand.appleDarkSurface|the iPhone keyboard's dark surface
Brand|apple/light-modifier|COLOR|#ADB3BC|||DesignTokens.Brand.appleLightModifier|the iPhone keyboard's light modifier key
Brand|apple/light-surface|COLOR|#D1D5DB|||DesignTokens.Brand.appleLightSurface|the iPhone keyboard's light surface
Brand|black|COLOR|#000000|||DesignTokens.Brand.black|
Brand|card|COLOR|#EBE8E8|||DesignTokens.Brand.card|the warm card fill; the paper theme's surface
Brand|card-border|COLOR|#DEDBDB|||DesignTokens.Brand.cardBorder|the card's hairline; the paper theme's modifier key
Brand|cobolt|COLOR|#3923C7|||DesignTokens.Brand.cobolt|AssemblyAI's primary violet: the drop, never a key or a surface
Brand|green/100|COLOR|#CCE4D5|||DesignTokens.Brand.green100|the design system's UI-and-code green fill (unused on the phone yet)
Brand|green/200|COLOR|#99C8AC|||DesignTokens.Brand.green200|the design system's UI-and-code green highlight (unused on the phone yet)
Brand|green/400|COLOR|#67AD82|||DesignTokens.Brand.green400|the brand hue lifted for dark chrome: the meter, the ring, the wave on ink
Brand|green/700|COLOR|#01762F|||DesignTokens.Brand.green700|the wordmark green, light chrome (the app's accent in light)
Brand|green/mist|COLOR|#DBF5E6|||DesignTokens.Brand.greenMist|the pale green the orb lightens into
Brand|ink|COLOR|#1D1B16|||DesignTokens.Brand.ink|the brand ink: the Mac pill's body, the ink theme's surface
Brand|ink/600|COLOR|#3A362F|||DesignTokens.Brand.ink600|the Mac's dark card border
Brand|ink/700|COLOR|#33302A|||DesignTokens.Brand.ink700|an ordinary key on ink, one step up
Brand|ink/800|COLOR|#26231E|||DesignTokens.Brand.ink800|a modifier key on ink; the Mac's dark card fill
Brand|orange|COLOR|#E67F36|||DesignTokens.Brand.orange|the error word and ring, cancel, the Full Access note; never a red body
Brand|page|COLOR|#FDFCF8|||DesignTokens.Brand.page|the design system's page background (unused on the phone)
Brand|violet/iris|COLOR|#887BDD|||DesignTokens.Brand.violetIris|the orb gradient's upper violet stop
Brand|violet/lavender|COLOR|#D7D3F4|||DesignTokens.Brand.violetLavender|the orb's lightest violet: its top and the gradient's ends
Brand|violet/periwinkle|COLOR|#B0A7E9|||DesignTokens.Brand.violetPeriwinkle|the orb's mid violet: the drop's halo
Brand|warm-white|COLOR|#F2EEE6|||DesignTokens.Brand.warmWhite|key legends on ink: warm white on warm ink
Brand|white|COLOR|#FFFFFF|||DesignTokens.Brand.white|
Themes|ink/key|COLOR|#33302A|Brand:ink/700||DesignTokens.Themes.inkKey|
Themes|ink/key-modifier|COLOR|#26231E|Brand:ink/800||DesignTokens.Themes.inkKeyModifier|
Themes|ink/legend|COLOR|#F2EEE6|Brand:warm-white||DesignTokens.Themes.inkLegend|
Themes|ink/popup|COLOR|#33302A|Brand:ink/700||DesignTokens.Themes.inkPopup|
Themes|ink/signal|COLOR|#67AD82|Brand:green/400||DesignTokens.Themes.inkSignal|
Themes|ink/surface|COLOR|#1D1B16|Brand:ink||DesignTokens.Themes.inkSurface|
Themes|lavender/key|COLOR|#3F3777|||DesignTokens.Themes.lavenderKey|
Themes|lavender/key-modifier|COLOR|#352E68|||DesignTokens.Themes.lavenderKeyModifier|
Themes|lavender/legend|COLOR|#F1EEFF|||DesignTokens.Themes.lavenderLegend|
Themes|lavender/popup|COLOR|#3F3777|||DesignTokens.Themes.lavenderPopup|
Themes|lavender/signal|COLOR|#67AD82|Brand:green/400||DesignTokens.Themes.lavenderSignal|
Themes|lavender/surface|COLOR|#2C2557|||DesignTokens.Themes.lavenderSurface|
Themes|midnight/key|COLOR|#1D2440|||DesignTokens.Themes.midnightKey|
Themes|midnight/key-modifier|COLOR|#161B33|||DesignTokens.Themes.midnightKeyModifier|
Themes|midnight/legend|COLOR|#E8ECFF|||DesignTokens.Themes.midnightLegend|
Themes|midnight/popup|COLOR|#1D2440|||DesignTokens.Themes.midnightPopup|
Themes|midnight/signal|COLOR|#67AD82|Brand:green/400||DesignTokens.Themes.midnightSignal|
Themes|midnight/surface|COLOR|#0E1220|||DesignTokens.Themes.midnightSurface|
Themes|mint/key|COLOR|#1E3F31|||DesignTokens.Themes.mintKey|
Themes|mint/key-modifier|COLOR|#183429|||DesignTokens.Themes.mintKeyModifier|
Themes|mint/legend|COLOR|#E9F5EE|||DesignTokens.Themes.mintLegend|
Themes|mint/popup|COLOR|#1E3F31|||DesignTokens.Themes.mintPopup|
Themes|mint/signal|COLOR|#67AD82|Brand:green/400||DesignTokens.Themes.mintSignal|
Themes|mint/surface|COLOR|#10231B|||DesignTokens.Themes.mintSurface|
Themes|paper/key|COLOR|#FFFFFF|Brand:white||DesignTokens.Themes.paperKey|
Themes|paper/key-modifier|COLOR|#DEDBDB|Brand:card-border||DesignTokens.Themes.paperKeyModifier|
Themes|paper/legend|COLOR|#1D1B16|Brand:ink||DesignTokens.Themes.paperLegend|
Themes|paper/popup|COLOR|#FFFFFF|Brand:white||DesignTokens.Themes.paperPopup|
Themes|paper/signal|COLOR|#01762F|Brand:green/700||DesignTokens.Themes.paperSignal|
Themes|paper/surface|COLOR|#EBE8E8|Brand:card||DesignTokens.Themes.paperSurface|
Themes|sunset/key|COLOR|#4B2B20|||DesignTokens.Themes.sunsetKey|
Themes|sunset/key-modifier|COLOR|#3B2119|||DesignTokens.Themes.sunsetKeyModifier|
Themes|sunset/legend|COLOR|#FFEFE6|||DesignTokens.Themes.sunsetLegend|
Themes|sunset/popup|COLOR|#4B2B20|||DesignTokens.Themes.sunsetPopup|
Themes|sunset/signal|COLOR|#67AD82|Brand:green/400||DesignTokens.Themes.sunsetSignal|
Themes|sunset/surface|COLOR|#2B1912|||DesignTokens.Themes.sunsetSurface|
Themes|system-dark/key|COLOR|#6B6B6B|Brand:apple/dark-key||DesignTokens.Themes.systemDarkKey|
Themes|system-dark/key-modifier|COLOR|#464646|Brand:apple/dark-modifier||DesignTokens.Themes.systemDarkKeyModifier|
Themes|system-dark/legend|COLOR|#FFFFFF|Brand:white||DesignTokens.Themes.systemDarkLegend|
Themes|system-dark/popup|COLOR|#6B6B6B|Brand:apple/dark-key||DesignTokens.Themes.systemDarkPopup|
Themes|system-dark/signal|COLOR|#67AD82|Brand:green/400||DesignTokens.Themes.systemDarkSignal|
Themes|system-dark/surface|COLOR|#2B2B2B|Brand:apple/dark-surface||DesignTokens.Themes.systemDarkSurface|
Themes|system-light/key|COLOR|#FFFFFF|Brand:white||DesignTokens.Themes.systemLightKey|
Themes|system-light/key-modifier|COLOR|#ADB3BC|Brand:apple/light-modifier||DesignTokens.Themes.systemLightKeyModifier|
Themes|system-light/legend|COLOR|#000000|Brand:black||DesignTokens.Themes.systemLightLegend|
Themes|system-light/popup|COLOR|#FFFFFF|Brand:white||DesignTokens.Themes.systemLightPopup|
Themes|system-light/signal|COLOR|#01762F|Brand:green/700||DesignTokens.Themes.systemLightSignal|
Themes|system-light/surface|COLOR|#D1D5DB|Brand:apple/light-surface||DesignTokens.Themes.systemLightSurface|
Keyboard|app/accent-dark|COLOR|#67AD82|Brand:green/400|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appAccentDark|the catalog's AccentColor in dark
Keyboard|app/accent-light|COLOR|#01762F|Brand:green/700|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appAccentLight|the catalog's AccentColor in light
Keyboard|app/card-border-dark|COLOR|#3A362F|Brand:ink/600|STROKE_COLOR|DesignTokens.Keyboard.appCardBorderDark|the catalog's CardBorder in dark
Keyboard|app/card-border-light|COLOR|#DEDBDB|Brand:card-border|STROKE_COLOR|DesignTokens.Keyboard.appCardBorderLight|the catalog's CardBorder in light
Keyboard|app/card-fill-dark|COLOR|#26231E|Brand:ink/800|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appCardFillDark|the catalog's CardFill in dark
Keyboard|app/card-fill-light|COLOR|#EBE8E8|Brand:card|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.appCardFillLight|the catalog's CardFill in light
Keyboard|kb/cancel|COLOR|#E67F36|Brand:orange|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.kbCancel|the panel's cancel ×
Keyboard|kb/full-access-note|COLOR|#E67F36|Brand:orange|TEXT_FILL|DesignTokens.Keyboard.kbFullAccessNote|the one line of words the keyboard ever shows
Keyboard|kb/key|COLOR|#33302A|Themes:ink/key|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.kbKey|an ordinary key
Keyboard|kb/key-modifier|COLOR|#26231E|Themes:ink/key-modifier|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.kbKeyModifier|shift, delete, globe, return, 123, cancel
Keyboard|kb/legend|COLOR|#F2EEE6|Themes:ink/legend|TEXT_FILL|DesignTokens.Keyboard.kbLegend|key legends and bare glyphs
Keyboard|kb/notice-error|COLOR|#E67F36|Brand:orange|STROKE_COLOR|DesignTokens.Keyboard.kbNoticeError|the solid ring and glyph for an error
Keyboard|kb/notice-ok|COLOR|#67AD82|Brand:green/400|STROKE_COLOR|DesignTokens.Keyboard.kbNoticeOk|the solid ring for pasted and copied
Keyboard|kb/orb-ring-end|COLOR|#FFFFFF|Brand:white|STROKE_COLOR|DesignTokens.Keyboard.kbOrbRingEnd|the sweeping ring's gradient, bottom-trailing
Keyboard|kb/orb-ring-start|COLOR|#01762F|Brand:green/700|STROKE_COLOR|DesignTokens.Keyboard.kbOrbRingStart|the sweeping ring's gradient, top-leading
Keyboard|kb/popup|COLOR|#33302A|Themes:ink/popup|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.kbPopup|the letter pop-up
Keyboard|kb/signal|COLOR|#67AD82|Themes:ink/signal|SHAPE_FILL,TEXT_FILL|DesignTokens.Keyboard.kbSignal|the wave, the caret, the saved check
Keyboard|kb/surface|COLOR|#1D1B16|Themes:ink/surface|FRAME_FILL,SHAPE_FILL|DesignTokens.Keyboard.kbSurface|the design theme's surface (Figma binds to kb/*; Swift reads the palette)
Metrics|addterm/inset|FLOAT|6||GAP|DesignTokens.Metrics.addtermInset|the + from the panel's corner
Metrics|card/border|FLOAT|1||STROKE_FLOAT,WIDTH_HEIGHT|DesignTokens.Metrics.cardBorder|the card's hairline
Metrics|card/radius|FLOAT|16||CORNER_RADIUS|DesignTokens.Metrics.cardRadius|the app's cards
Metrics|caret/height|FLOAT|20||WIDTH_HEIGHT|DesignTokens.Metrics.caretHeight|
Metrics|caret/lead|FLOAT|1||GAP|DesignTokens.Metrics.caretLead|the caret's gap from the text
Metrics|caret/radius|FLOAT|1||CORNER_RADIUS|DesignTokens.Metrics.caretRadius|
Metrics|caret/width|FLOAT|2||STROKE_FLOAT,WIDTH_HEIGHT|DesignTokens.Metrics.caretWidth|
Metrics|gesture/swipe-min|FLOAT|24|||DesignTokens.Metrics.gestureSwipeMin|the carousel gesture's minimum distance
Metrics|glyph/hit|FLOAT|32||WIDTH_HEIGHT|DesignTokens.Metrics.glyphHit|the +, × and ✓ touch targets
Metrics|key/gap|FLOAT|6||GAP|DesignTokens.Metrics.keyGap|between keys, the iPhone's
Metrics|key/height|FLOAT|42||WIDTH_HEIGHT|DesignTokens.Metrics.keyHeight|every key
Metrics|key/letter-width-402|FLOAT|34.8||WIDTH_HEIGHT|DesignTokens.Metrics.keyLetterWidth402|a letter key at 402 pt (iPhone 18 Pro): (width − 9 × key/gap) / 10
Metrics|key/min-width|FLOAT|44||WIDTH_HEIGHT|DesignTokens.Metrics.keyMinWidth|a key that isn't given a width
Metrics|key/pad|FLOAT|4||GAP|DesignTokens.Metrics.keyPad|a legend's side padding on a min-width key
Metrics|key/radius|FLOAT|8||CORNER_RADIUS|DesignTokens.Metrics.keyRadius|flat keys, one colour at this corner
Metrics|key/return-width-402|FLOAT|104.4||WIDTH_HEIGHT|DesignTokens.Metrics.keyReturnWidth402|return at 402 pt: two side keys and a gap
Metrics|key/side-gap-factor|FLOAT|2|||DesignTokens.Metrics.keySideGapFactor|shift and delete stand this many key gaps from the letters
Metrics|key/side-width-402|FLOAT|49.2||WIDTH_HEIGHT|DesignTokens.Metrics.keySideWidth402|shift, delete, 123 and globe at 402 pt: what seven letters leave, halved
Metrics|layout/full|FLOAT|272||WIDTH_HEIGHT|DesignTokens.Metrics.layoutFull|2 × margin/vertical + voicebar/height + 4 × row/gap + 4 × key/height
Metrics|layout/panel|FLOAT|216||WIDTH_HEIGHT|DesignTokens.Metrics.layoutPanel|chosen: room for the 96 orb over one key row
Metrics|layout/slim|FLOAT|60||WIDTH_HEIGHT|DesignTokens.Metrics.layoutSlim|2 × margin/vertical + voicebar/height
Metrics|margin/side|FLOAT|3||WIDTH_HEIGHT|DesignTokens.Metrics.marginSide|at the keyboard's sides
Metrics|margin/vertical|FLOAT|8||WIDTH_HEIGHT|DesignTokens.Metrics.marginVertical|the keyboard's top and bottom
Metrics|opacity/dim|FLOAT|0.8||OPACITY|DesignTokens.Metrics.opacityDim|the orb when Blurt isn't ready
Metrics|opacity/dim-saturation|FLOAT|0.35||OPACITY|DesignTokens.Metrics.opacityDimSaturation|and its saturation
Metrics|opacity/disabled|FLOAT|0.4||OPACITY|DesignTokens.Metrics.opacityDisabled|the + without Full Access
Metrics|opacity/grain|FLOAT|0.5||OPACITY|DesignTokens.Metrics.opacityGrain|
Metrics|opacity/home-dim-saturation|FLOAT|0.45||OPACITY|DesignTokens.Metrics.opacityHomeDimSaturation|the home hero's saturation when not listening
Metrics|opacity/legend|FLOAT|1||OPACITY|DesignTokens.Metrics.opacityLegend|key legends over the cap; below 1 they sit back
Metrics|opacity/legend-muted|FLOAT|0.5||OPACITY|DesignTokens.Metrics.opacityLegendMuted|the + at rest
Metrics|opacity/orb-light|FLOAT|0.3||OPACITY|DesignTokens.Metrics.opacityOrbLight|
Metrics|opacity/placeholder|FLOAT|0.4||OPACITY|DesignTokens.Metrics.opacityPlaceholder|the field's placeholder
Metrics|opacity/popup-shadow|FLOAT|0.12||OPACITY|DesignTokens.Metrics.opacityPopupShadow|
Metrics|opacity/press-brighten|FLOAT|0.15||OPACITY|DesignTokens.Metrics.opacityPressBrighten|a key lightens this much while pressed
Metrics|opacity/surface-grain|FLOAT|0.14||OPACITY|DesignTokens.Metrics.opacitySurfaceGrain|film grain over the whole keyboard surface: matte, the brand's texture
Metrics|opacity/surface-vignette|FLOAT|0||OPACITY|DesignTokens.Metrics.opacitySurfaceVignette|a soft darkening toward the surface's edges; 0 is none
Metrics|opacity/term-cancel|FLOAT|0.7||OPACITY|DesignTokens.Metrics.opacityTermCancel|the field's ×
Metrics|orb/bar|FLOAT|40||WIDTH_HEIGHT|DesignTokens.Metrics.orbBar|the orb in the voice bar
Metrics|orb/dissipate-blur|FLOAT|0.16|||DesignTokens.Metrics.orbDissipateBlur|and blurs to this fraction of its size
Metrics|orb/dissipate-scale|FLOAT|1.25|||DesignTokens.Metrics.orbDissipateScale|the orb swells to this while dissipating
Metrics|orb/home|FLOAT|112||WIDTH_HEIGHT|DesignTokens.Metrics.orbHome|the orb on the home screen
Metrics|orb/light-reach|FLOAT|0.9|||DesignTokens.Metrics.orbLightReach|the soft light's reach, as a fraction of the orb (was a fixed 110 pt, flat on a 40 pt orb)
Metrics|orb/light-x|FLOAT|0.3|||DesignTokens.Metrics.orbLightX|the soft light's centre, as a fraction of the orb
Metrics|orb/light-y|FLOAT|0.22|||DesignTokens.Metrics.orbLightY|
Metrics|orb/panel|FLOAT|96||WIDTH_HEIGHT|DesignTokens.Metrics.orbPanel|the orb in the panel
Metrics|panel/spacing|FLOAT|12||GAP|DesignTokens.Metrics.panelSpacing|between the panel's orb and its key row
Metrics|picker/preview-width|FLOAT|393||WIDTH_HEIGHT|DesignTokens.Metrics.pickerPreviewWidth|the theme card draws the keyboard at this width
Metrics|picker/radius|FLOAT|10||CORNER_RADIUS|DesignTokens.Metrics.pickerRadius|the theme card's preview corners
Metrics|picker/scale|FLOAT|0.42|||DesignTokens.Metrics.pickerScale|then scales it to fit two across
Metrics|popup/extra-width|FLOAT|18||WIDTH_HEIGHT|DesignTokens.Metrics.popupExtraWidth|the letter pop-up is the key width plus this
Metrics|popup/height|FLOAT|56||WIDTH_HEIGHT|DesignTokens.Metrics.popupHeight|
Metrics|popup/offset|FLOAT|58||WIDTH_HEIGHT|DesignTokens.Metrics.popupOffset|the pop-up sits this far above the key
Metrics|popup/radius|FLOAT|10||CORNER_RADIUS|DesignTokens.Metrics.popupRadius|
Metrics|popup/shadow-radius|FLOAT|8||WIDTH_HEIGHT|DesignTokens.Metrics.popupShadowRadius|the one thing that floats
Metrics|popup/shadow-y|FLOAT|2||WIDTH_HEIGHT|DesignTokens.Metrics.popupShadowY|
Metrics|press/scale|FLOAT|0.94|||DesignTokens.Metrics.pressScale|the orb while pressed
Metrics|ring/active|FLOAT|2||STROKE_FLOAT,WIDTH_HEIGHT|DesignTokens.Metrics.ringActive|the ring while working or noticing; the home ring
Metrics|ring/still|FLOAT|1||STROKE_FLOAT,WIDTH_HEIGHT|DesignTokens.Metrics.ringStill|the ring at rest
Metrics|row/gap|FLOAT|11||GAP|DesignTokens.Metrics.rowGap|between rows, the iPhone's
Metrics|slim/spacing|FLOAT|8||GAP|DesignTokens.Metrics.slimSpacing|between the slim bar's keys
Metrics|surface/vignette-end|FLOAT|0.75||WIDTH_HEIGHT|DesignTokens.Metrics.surfaceVignetteEnd|where it is full
Metrics|surface/vignette-start|FLOAT|0.3||WIDTH_HEIGHT|DesignTokens.Metrics.surfaceVignetteStart|where the vignette begins, as a fraction of the keyboard's width
Metrics|term/gap|FLOAT|8||GAP|DesignTokens.Metrics.termGap|× · field · ✓
Metrics|term/height|FLOAT|36||WIDTH_HEIGHT|DesignTokens.Metrics.termHeight|the key-term field's capsule
Metrics|term/inset|FLOAT|2||GAP|DesignTokens.Metrics.termInset|the field row's side inset
Metrics|term/pad|FLOAT|14||GAP|DesignTokens.Metrics.termPad|the field's side padding
Metrics|voicebar/addterm-clearance|FLOAT|12||GAP|DesignTokens.Metrics.voicebarAddtermClearance|the wave stays this clear of the + at the trailing edge
Metrics|voicebar/height|FLOAT|44||WIDTH_HEIGHT|DesignTokens.Metrics.voicebarHeight|the voice row, where the system puts its suggestion bar
Metrics|voicebar/note-gap|FLOAT|10||GAP|DesignTokens.Metrics.voicebarNoteGap|between the orb and the Full Access note
Metrics|wave/bar|FLOAT|2||STROKE_FLOAT,WIDTH_HEIGHT|DesignTokens.Metrics.waveBar|a wave bar's width
Metrics|wave/bar-height|FLOAT|24||WIDTH_HEIGHT|DesignTokens.Metrics.waveBarHeight|
Metrics|wave/bar-width|FLOAT|240||WIDTH_HEIGHT|DesignTokens.Metrics.waveBarWidth|the wave in the voice bar, at most
Metrics|wave/gap|FLOAT|2||GAP|DesignTokens.Metrics.waveGap|between wave bars
Metrics|wave/home-height|FLOAT|44||WIDTH_HEIGHT|DesignTokens.Metrics.waveHomeHeight|
Metrics|wave/home-width|FLOAT|280||WIDTH_HEIGHT|DesignTokens.Metrics.waveHomeWidth|
Metrics|wave/liquid|FLOAT|0||WIDTH_HEIGHT|DesignTokens.Metrics.waveLiquid|1 draws the wave as one liquid shape through the bar heights instead of the bars themselves
Metrics|wave/panel-height|FLOAT|40||WIDTH_HEIGHT|DesignTokens.Metrics.wavePanelHeight|
Metrics|wave/panel-width|FLOAT|300||WIDTH_HEIGHT|DesignTokens.Metrics.wavePanelWidth|
Metrics|wordmark/height|FLOAT|22||WIDTH_HEIGHT|DesignTokens.Metrics.wordmarkHeight|
Typography|ratio/orb-glyph|FLOAT|0.34|||DesignTokens.Typography.ratioOrbGlyph|the clipboard and exclamation glyphs, as a fraction of the orb
Typography|size/glyph|FLOAT|17||FONT_SIZE|DesignTokens.Typography.sizeGlyph|the +, × and ✓
Typography|size/legend|FLOAT|16||FONT_SIZE|DesignTokens.Typography.sizeLegend|every other key
Typography|size/letter|FLOAT|22||FONT_SIZE|DesignTokens.Typography.sizeLetter|letter keys
Typography|size/popup|FLOAT|32||FONT_SIZE|DesignTokens.Typography.sizePopup|the letter pop-up
Typography|size/term|FLOAT|17||FONT_SIZE|DesignTokens.Typography.sizeTerm|the key-term field
Typography|weight/glyph|STRING|medium||FONT_STYLE|DesignTokens.Typography.weightGlyph|
Typography|weight/legend|STRING|medium||FONT_STYLE|DesignTokens.Typography.weightLegend|
Typography|weight/letter|STRING|regular||FONT_STYLE|DesignTokens.Typography.weightLetter|
Typography|weight/orb-glyph|STRING|semibold||FONT_STYLE|DesignTokens.Typography.weightOrbGlyph|
Typography|weight/popup|STRING|regular||FONT_STYLE|DesignTokens.Typography.weightPopup|
Typography|weight/term|STRING|regular||FONT_STYLE|DesignTokens.Typography.weightTerm|
Motion|caret|FLOAT|0.5|||DesignTokens.Motion.caret|the caret's blink
Motion|drop|FLOAT|2.4|||DesignTokens.Motion.drop|the violet drop is gone by
Motion|drop-hold|FLOAT|0.9|||DesignTokens.Motion.dropHold|and held to
Motion|drop-rise|FLOAT|0.5|||DesignTokens.Motion.dropRise|the drop is up in
Motion|drop-spread|FLOAT|1|||DesignTokens.Motion.dropSpread|the bloom reaches its full spread in
Motion|flip|FLOAT|0.25|||DesignTokens.Motion.flip|the panel's carousel
Motion|height-change|FLOAT|0.25|||DesignTokens.Motion.heightChange|the keyboard resizing
Motion|key-press|FLOAT|0.08|||DesignTokens.Motion.keyPress|a key lighting
Motion|mood|FLOAT|0.8|||DesignTokens.Motion.mood|the orb's colour moving between moods
Motion|press|FLOAT|0.1|||DesignTokens.Motion.press|the orb's press; the one thing that answers at once
Motion|ring-period|FLOAT|1.6|||DesignTokens.Motion.ringPeriod|one turn of the ring, the Mac's cadence
Motion|state-fade|FLOAT|0.5|||DesignTokens.Motion.stateFade|every other change on the key: the ring, a glyph, the dimming
Motion|term-swap|FLOAT|0.4|||DesignTokens.Motion.termSwap|the voice bar becoming the field
Motion|wave-fade|FLOAT|0.7|||DesignTokens.Motion.waveFade|the orb and the wave crossing, either way
GRADIENT|orb|bottom|top|#D7D3F4@0,#B0A7E9@0.0673,#67AD82@0.1442,#01762F@0.3029,#3923C7@0.5962,#887BDD@0.75,#D7D3F4@0.8942,#FFFFFF@1|the Mac orb's fill, the design's own stops (App elements/Recording.svg), swept bottom to top
GRADIENT|orb-ring|topLeading|bottomTrailing|#01762F@0,#FFFFFF@1|the ring round the orb: green into white, corner to corner; spun while something is happening`;
const GROUPS = ["Brand", "Themes", "Keyboard", "Metrics", "Typography", "Motion"];
