// Generated by scripts/design-tokens.swift from App/BlurtiOS/Design/tokens.json — do not edit.
// The build scripts in this folder (lib.js) read this; a use_figma call is
// tokens.js + lib.js + one line that returns a builder's result.
const TOKENS = {
  "collections" : {
    "Brand" : {
      "mode" : "Value",
      "variables" : [
        {
          "codeSyntax" : "DesignTokens.Brand.appleDarkKey",
          "name" : "apple\/dark-key",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the iPhone keyboard's dark key",
          "value" : "#6B6B6B"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.appleDarkModifier",
          "name" : "apple\/dark-modifier",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the iPhone keyboard's dark modifier key",
          "value" : "#464646"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.appleDarkSurface",
          "name" : "apple\/dark-surface",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the iPhone keyboard's dark surface",
          "value" : "#2B2B2B"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.appleLightModifier",
          "name" : "apple\/light-modifier",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the iPhone keyboard's light modifier key",
          "value" : "#ADB3BC"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.appleLightSurface",
          "name" : "apple\/light-surface",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the iPhone keyboard's light surface",
          "value" : "#D1D5DB"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.black",
          "name" : "black",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#000000"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.card",
          "name" : "card",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the warm card fill; the paper theme's surface",
          "value" : "#EBE8E8"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.cardBorder",
          "name" : "card-border",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the card's hairline; the paper theme's modifier key",
          "value" : "#DEDBDB"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.cobolt",
          "name" : "cobolt",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "AssemblyAI's primary violet: the drop, never a key or a surface",
          "value" : "#3923C7"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.green100",
          "name" : "green\/100",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the design system's UI-and-code green fill (unused on the phone yet)",
          "value" : "#CCE4D5"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.green200",
          "name" : "green\/200",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the design system's UI-and-code green highlight (unused on the phone yet)",
          "value" : "#99C8AC"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.green400",
          "name" : "green\/400",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the brand hue lifted for dark chrome: the meter, the ring, the wave on ink",
          "value" : "#67AD82"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.green700",
          "name" : "green\/700",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the wordmark green, light chrome (the app's accent in light)",
          "value" : "#01762F"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.greenMist",
          "name" : "green\/mist",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the pale green the orb lightens into",
          "value" : "#DBF5E6"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.ink",
          "name" : "ink",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the brand ink: the Mac pill's body, the ink theme's surface",
          "value" : "#1D1B16"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.ink600",
          "name" : "ink\/600",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the Mac's dark card border",
          "value" : "#3A362F"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.ink700",
          "name" : "ink\/700",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "an ordinary key on ink, one step up",
          "value" : "#33302A"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.ink800",
          "name" : "ink\/800",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "a modifier key on ink; the Mac's dark card fill",
          "value" : "#26231E"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.orange",
          "name" : "orange",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the error word and ring, cancel, the Full Access note; never a red body",
          "value" : "#E67F36"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.page",
          "name" : "page",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the design system's page background (unused on the phone)",
          "value" : "#FDFCF8"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.violetIris",
          "name" : "violet\/iris",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the orb gradient's upper violet stop",
          "value" : "#887BDD"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.violetLavender",
          "name" : "violet\/lavender",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the orb's lightest violet: its top and the gradient's ends",
          "value" : "#D7D3F4"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.violetPeriwinkle",
          "name" : "violet\/periwinkle",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "the orb's mid violet: the drop's halo",
          "value" : "#B0A7E9"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.warmWhite",
          "name" : "warm-white",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "key legends on ink: warm white on warm ink",
          "value" : "#F2EEE6"
        },
        {
          "codeSyntax" : "DesignTokens.Brand.white",
          "name" : "white",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#FFFFFF"
        }
      ]
    },
    "Keyboard" : {
      "mode" : "Value",
      "variables" : [
        {
          "alias" : "Brand:green\/400",
          "codeSyntax" : "DesignTokens.Keyboard.appAccentDark",
          "name" : "app\/accent-dark",
          "scopes" : [
            "FRAME_FILL",
            "SHAPE_FILL"
          ],
          "type" : "COLOR",
          "use" : "the catalog's AccentColor in dark",
          "value" : "#67AD82"
        },
        {
          "alias" : "Brand:green\/700",
          "codeSyntax" : "DesignTokens.Keyboard.appAccentLight",
          "name" : "app\/accent-light",
          "scopes" : [
            "FRAME_FILL",
            "SHAPE_FILL"
          ],
          "type" : "COLOR",
          "use" : "the catalog's AccentColor in light",
          "value" : "#01762F"
        },
        {
          "alias" : "Brand:ink\/600",
          "codeSyntax" : "DesignTokens.Keyboard.appCardBorderDark",
          "name" : "app\/card-border-dark",
          "scopes" : [
            "STROKE_COLOR"
          ],
          "type" : "COLOR",
          "use" : "the catalog's CardBorder in dark",
          "value" : "#3A362F"
        },
        {
          "alias" : "Brand:card-border",
          "codeSyntax" : "DesignTokens.Keyboard.appCardBorderLight",
          "name" : "app\/card-border-light",
          "scopes" : [
            "STROKE_COLOR"
          ],
          "type" : "COLOR",
          "use" : "the catalog's CardBorder in light",
          "value" : "#DEDBDB"
        },
        {
          "alias" : "Brand:ink\/800",
          "codeSyntax" : "DesignTokens.Keyboard.appCardFillDark",
          "name" : "app\/card-fill-dark",
          "scopes" : [
            "FRAME_FILL",
            "SHAPE_FILL"
          ],
          "type" : "COLOR",
          "use" : "the catalog's CardFill in dark",
          "value" : "#26231E"
        },
        {
          "alias" : "Brand:card",
          "codeSyntax" : "DesignTokens.Keyboard.appCardFillLight",
          "name" : "app\/card-fill-light",
          "scopes" : [
            "FRAME_FILL",
            "SHAPE_FILL"
          ],
          "type" : "COLOR",
          "use" : "the catalog's CardFill in light",
          "value" : "#EBE8E8"
        },
        {
          "alias" : "Brand:orange",
          "codeSyntax" : "DesignTokens.Keyboard.kbCancel",
          "name" : "kb\/cancel",
          "scopes" : [
            "FRAME_FILL",
            "SHAPE_FILL"
          ],
          "type" : "COLOR",
          "use" : "the panel's cancel ×",
          "value" : "#E67F36"
        },
        {
          "alias" : "Brand:orange",
          "codeSyntax" : "DesignTokens.Keyboard.kbFullAccessNote",
          "name" : "kb\/full-access-note",
          "scopes" : [
            "TEXT_FILL"
          ],
          "type" : "COLOR",
          "use" : "the one line of words the keyboard ever shows",
          "value" : "#E67F36"
        },
        {
          "alias" : "Themes:ink\/key",
          "codeSyntax" : "DesignTokens.Keyboard.kbKey",
          "name" : "kb\/key",
          "scopes" : [
            "FRAME_FILL",
            "SHAPE_FILL"
          ],
          "type" : "COLOR",
          "use" : "an ordinary key",
          "value" : "#33302A"
        },
        {
          "alias" : "Themes:ink\/key-modifier",
          "codeSyntax" : "DesignTokens.Keyboard.kbKeyModifier",
          "name" : "kb\/key-modifier",
          "scopes" : [
            "FRAME_FILL",
            "SHAPE_FILL"
          ],
          "type" : "COLOR",
          "use" : "shift, delete, globe, return, 123, cancel",
          "value" : "#26231E"
        },
        {
          "alias" : "Themes:ink\/legend",
          "codeSyntax" : "DesignTokens.Keyboard.kbLegend",
          "name" : "kb\/legend",
          "scopes" : [
            "TEXT_FILL"
          ],
          "type" : "COLOR",
          "use" : "key legends and bare glyphs",
          "value" : "#F2EEE6"
        },
        {
          "alias" : "Brand:orange",
          "codeSyntax" : "DesignTokens.Keyboard.kbNoticeError",
          "name" : "kb\/notice-error",
          "scopes" : [
            "STROKE_COLOR"
          ],
          "type" : "COLOR",
          "use" : "the solid ring and glyph for an error",
          "value" : "#E67F36"
        },
        {
          "alias" : "Brand:green\/400",
          "codeSyntax" : "DesignTokens.Keyboard.kbNoticeOk",
          "name" : "kb\/notice-ok",
          "scopes" : [
            "STROKE_COLOR"
          ],
          "type" : "COLOR",
          "use" : "the solid ring for pasted and copied",
          "value" : "#67AD82"
        },
        {
          "alias" : "Brand:white",
          "codeSyntax" : "DesignTokens.Keyboard.kbOrbRingEnd",
          "name" : "kb\/orb-ring-end",
          "scopes" : [
            "STROKE_COLOR"
          ],
          "type" : "COLOR",
          "use" : "the sweeping ring's gradient, bottom-trailing",
          "value" : "#FFFFFF"
        },
        {
          "alias" : "Brand:green\/700",
          "codeSyntax" : "DesignTokens.Keyboard.kbOrbRingStart",
          "name" : "kb\/orb-ring-start",
          "scopes" : [
            "STROKE_COLOR"
          ],
          "type" : "COLOR",
          "use" : "the sweeping ring's gradient, top-leading",
          "value" : "#01762F"
        },
        {
          "alias" : "Themes:ink\/popup",
          "codeSyntax" : "DesignTokens.Keyboard.kbPopup",
          "name" : "kb\/popup",
          "scopes" : [
            "FRAME_FILL",
            "SHAPE_FILL"
          ],
          "type" : "COLOR",
          "use" : "the letter pop-up",
          "value" : "#33302A"
        },
        {
          "alias" : "Themes:ink\/signal",
          "codeSyntax" : "DesignTokens.Keyboard.kbSignal",
          "name" : "kb\/signal",
          "scopes" : [
            "SHAPE_FILL",
            "TEXT_FILL"
          ],
          "type" : "COLOR",
          "use" : "the wave, the caret, the saved check",
          "value" : "#67AD82"
        },
        {
          "alias" : "Themes:ink\/surface",
          "codeSyntax" : "DesignTokens.Keyboard.kbSurface",
          "name" : "kb\/surface",
          "scopes" : [
            "FRAME_FILL",
            "SHAPE_FILL"
          ],
          "type" : "COLOR",
          "use" : "the design theme's surface (Figma binds to kb\/*; Swift reads the palette)",
          "value" : "#1D1B16"
        }
      ]
    },
    "Metrics" : {
      "mode" : "Value",
      "variables" : [
        {
          "codeSyntax" : "DesignTokens.Metrics.addtermInset",
          "name" : "addterm\/inset",
          "scopes" : [
            "GAP"
          ],
          "type" : "FLOAT",
          "use" : "the + from the panel's corner",
          "value" : 6
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.cardBorder",
          "name" : "card\/border",
          "scopes" : [
            "STROKE_FLOAT",
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the card's hairline",
          "value" : 1
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.cardRadius",
          "name" : "card\/radius",
          "scopes" : [
            "CORNER_RADIUS"
          ],
          "type" : "FLOAT",
          "use" : "the app's cards",
          "value" : 16
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.caretHeight",
          "name" : "caret\/height",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 20
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.caretLead",
          "name" : "caret\/lead",
          "scopes" : [
            "GAP"
          ],
          "type" : "FLOAT",
          "use" : "the caret's gap from the text",
          "value" : 1
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.caretRadius",
          "name" : "caret\/radius",
          "scopes" : [
            "CORNER_RADIUS"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 1
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.caretWidth",
          "name" : "caret\/width",
          "scopes" : [
            "STROKE_FLOAT",
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 2
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.gestureSwipeMin",
          "name" : "gesture\/swipe-min",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the carousel gesture's minimum distance",
          "value" : 24
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.glyphHit",
          "name" : "glyph\/hit",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the +, × and ✓ touch targets",
          "value" : 32
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.keyGap",
          "name" : "key\/gap",
          "scopes" : [
            "GAP"
          ],
          "type" : "FLOAT",
          "use" : "between keys, the iPhone's",
          "value" : 6
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.keyHeight",
          "name" : "key\/height",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "every key",
          "value" : 42
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.keyLetterWidth402",
          "name" : "key\/letter-width-402",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "a letter key at 402 pt (iPhone 18 Pro): (width − 9 × key\/gap) \/ 10",
          "value" : 34.799999999999997
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.keyMinWidth",
          "name" : "key\/min-width",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "a key that isn't given a width",
          "value" : 44
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.keyPad",
          "name" : "key\/pad",
          "scopes" : [
            "GAP"
          ],
          "type" : "FLOAT",
          "use" : "a legend's side padding on a min-width key",
          "value" : 4
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.keyRadius",
          "name" : "key\/radius",
          "scopes" : [
            "CORNER_RADIUS"
          ],
          "type" : "FLOAT",
          "use" : "flat keys, one colour at this corner",
          "value" : 8
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.keyReturnWidth402",
          "name" : "key\/return-width-402",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "return at 402 pt: two side keys and a gap",
          "value" : 104.40000000000001
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.keySideGapFactor",
          "name" : "key\/side-gap-factor",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "shift and delete stand this many key gaps from the letters",
          "value" : 2
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.keySideWidth402",
          "name" : "key\/side-width-402",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "shift, delete, 123 and globe at 402 pt: what seven letters leave, halved",
          "value" : 49.200000000000003
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.layoutFull",
          "name" : "layout\/full",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "2 × margin\/vertical + voicebar\/height + 4 × row\/gap + 4 × key\/height",
          "value" : 272
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.layoutPanel",
          "name" : "layout\/panel",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "chosen: room for the 96 orb over one key row",
          "value" : 216
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.layoutSlim",
          "name" : "layout\/slim",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "2 × margin\/vertical + voicebar\/height",
          "value" : 60
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.marginSide",
          "name" : "margin\/side",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "at the keyboard's sides",
          "value" : 3
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.marginVertical",
          "name" : "margin\/vertical",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the keyboard's top and bottom",
          "value" : 8
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.opacityDim",
          "name" : "opacity\/dim",
          "scopes" : [
            "OPACITY"
          ],
          "type" : "FLOAT",
          "use" : "the orb when Blurt isn't ready",
          "value" : 0.80000000000000004
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.opacityDimSaturation",
          "name" : "opacity\/dim-saturation",
          "scopes" : [
            "OPACITY"
          ],
          "type" : "FLOAT",
          "use" : "and its saturation",
          "value" : 0.34999999999999998
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.opacityDisabled",
          "name" : "opacity\/disabled",
          "scopes" : [
            "OPACITY"
          ],
          "type" : "FLOAT",
          "use" : "the + without Full Access",
          "value" : 0.40000000000000002
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.opacityGrain",
          "name" : "opacity\/grain",
          "scopes" : [
            "OPACITY"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 0.5
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.opacityHomeDimSaturation",
          "name" : "opacity\/home-dim-saturation",
          "scopes" : [
            "OPACITY"
          ],
          "type" : "FLOAT",
          "use" : "the home hero's saturation when not listening",
          "value" : 0.45000000000000001
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.opacityLegendMuted",
          "name" : "opacity\/legend-muted",
          "scopes" : [
            "OPACITY"
          ],
          "type" : "FLOAT",
          "use" : "the + at rest",
          "value" : 0.5
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.opacityOrbLight",
          "name" : "opacity\/orb-light",
          "scopes" : [
            "OPACITY"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 0.29999999999999999
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.opacityPlaceholder",
          "name" : "opacity\/placeholder",
          "scopes" : [
            "OPACITY"
          ],
          "type" : "FLOAT",
          "use" : "the field's placeholder",
          "value" : 0.40000000000000002
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.opacityPopupShadow",
          "name" : "opacity\/popup-shadow",
          "scopes" : [
            "OPACITY"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 0.12
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.opacityPressBrighten",
          "name" : "opacity\/press-brighten",
          "scopes" : [
            "OPACITY"
          ],
          "type" : "FLOAT",
          "use" : "a key lightens this much while pressed",
          "value" : 0.14999999999999999
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.opacityTermCancel",
          "name" : "opacity\/term-cancel",
          "scopes" : [
            "OPACITY"
          ],
          "type" : "FLOAT",
          "use" : "the field's ×",
          "value" : 0.69999999999999996
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.orbBar",
          "name" : "orb\/bar",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the orb in the voice bar",
          "value" : 40
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.orbDissipateBlur",
          "name" : "orb\/dissipate-blur",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "and blurs to this fraction of its size",
          "value" : 0.16
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.orbDissipateScale",
          "name" : "orb\/dissipate-scale",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the orb swells to this while dissipating",
          "value" : 1.25
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.orbHome",
          "name" : "orb\/home",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the orb on the home screen",
          "value" : 112
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.orbLightRadius",
          "name" : "orb\/light-radius",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the light's reach in points (fixed, not proportional — open)",
          "value" : 110
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.orbLightX",
          "name" : "orb\/light-x",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the soft light's centre, as a fraction of the orb",
          "value" : 0.29999999999999999
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.orbLightY",
          "name" : "orb\/light-y",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 0.22
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.orbPanel",
          "name" : "orb\/panel",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the orb in the panel",
          "value" : 96
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.panelSpacing",
          "name" : "panel\/spacing",
          "scopes" : [
            "GAP"
          ],
          "type" : "FLOAT",
          "use" : "between the panel's orb and its key row",
          "value" : 12
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.pickerPreviewWidth",
          "name" : "picker\/preview-width",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the theme card draws the keyboard at this width",
          "value" : 393
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.pickerRadius",
          "name" : "picker\/radius",
          "scopes" : [
            "CORNER_RADIUS"
          ],
          "type" : "FLOAT",
          "use" : "the theme card's preview corners",
          "value" : 10
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.pickerScale",
          "name" : "picker\/scale",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "then scales it to fit two across",
          "value" : 0.41999999999999998
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.popupExtraWidth",
          "name" : "popup\/extra-width",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the letter pop-up is the key width plus this",
          "value" : 18
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.popupHeight",
          "name" : "popup\/height",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 56
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.popupOffset",
          "name" : "popup\/offset",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the pop-up sits this far above the key",
          "value" : 58
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.popupRadius",
          "name" : "popup\/radius",
          "scopes" : [
            "CORNER_RADIUS"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 10
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.popupShadowRadius",
          "name" : "popup\/shadow-radius",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the one thing that floats",
          "value" : 8
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.popupShadowY",
          "name" : "popup\/shadow-y",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 2
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.pressScale",
          "name" : "press\/scale",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the orb while pressed",
          "value" : 0.93999999999999995
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.ringActive",
          "name" : "ring\/active",
          "scopes" : [
            "STROKE_FLOAT",
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the ring while working or noticing; the home ring",
          "value" : 2
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.ringStill",
          "name" : "ring\/still",
          "scopes" : [
            "STROKE_FLOAT",
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the ring at rest",
          "value" : 1
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.rowGap",
          "name" : "row\/gap",
          "scopes" : [
            "GAP"
          ],
          "type" : "FLOAT",
          "use" : "between rows, the iPhone's",
          "value" : 11
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.slimSpacing",
          "name" : "slim\/spacing",
          "scopes" : [
            "GAP"
          ],
          "type" : "FLOAT",
          "use" : "between the slim bar's keys",
          "value" : 8
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.termGap",
          "name" : "term\/gap",
          "scopes" : [
            "GAP"
          ],
          "type" : "FLOAT",
          "use" : "× · field · ✓",
          "value" : 8
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.termHeight",
          "name" : "term\/height",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the key-term field's capsule",
          "value" : 36
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.termInset",
          "name" : "term\/inset",
          "scopes" : [
            "GAP"
          ],
          "type" : "FLOAT",
          "use" : "the field row's side inset",
          "value" : 2
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.termPad",
          "name" : "term\/pad",
          "scopes" : [
            "GAP"
          ],
          "type" : "FLOAT",
          "use" : "the field's side padding",
          "value" : 14
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.voicebarAddtermClearance",
          "name" : "voicebar\/addterm-clearance",
          "scopes" : [
            "GAP"
          ],
          "type" : "FLOAT",
          "use" : "the wave stays this clear of the + at the trailing edge",
          "value" : 12
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.voicebarHeight",
          "name" : "voicebar\/height",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the voice row, where the system puts its suggestion bar",
          "value" : 44
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.voicebarNoteGap",
          "name" : "voicebar\/note-gap",
          "scopes" : [
            "GAP"
          ],
          "type" : "FLOAT",
          "use" : "between the orb and the Full Access note",
          "value" : 10
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.waveBar",
          "name" : "wave\/bar",
          "scopes" : [
            "STROKE_FLOAT",
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "a wave bar's width",
          "value" : 2
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.waveBarHeight",
          "name" : "wave\/bar-height",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 24
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.waveBarWidth",
          "name" : "wave\/bar-width",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "the wave in the voice bar, at most",
          "value" : 240
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.waveGap",
          "name" : "wave\/gap",
          "scopes" : [
            "GAP"
          ],
          "type" : "FLOAT",
          "use" : "between wave bars",
          "value" : 2
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.waveHomeHeight",
          "name" : "wave\/home-height",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 44
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.waveHomeWidth",
          "name" : "wave\/home-width",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 280
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.wavePanelHeight",
          "name" : "wave\/panel-height",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 40
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.wavePanelWidth",
          "name" : "wave\/panel-width",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 300
        },
        {
          "codeSyntax" : "DesignTokens.Metrics.wordmarkHeight",
          "name" : "wordmark\/height",
          "scopes" : [
            "WIDTH_HEIGHT"
          ],
          "type" : "FLOAT",
          "use" : "",
          "value" : 22
        }
      ]
    },
    "Motion" : {
      "mode" : "Value",
      "variables" : [
        {
          "codeSyntax" : "DesignTokens.Motion.caret",
          "name" : "caret",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the caret's blink",
          "value" : 0.5
        },
        {
          "codeSyntax" : "DesignTokens.Motion.drop",
          "name" : "drop",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the violet drop is gone by",
          "value" : 2.3999999999999999
        },
        {
          "codeSyntax" : "DesignTokens.Motion.dropHold",
          "name" : "drop-hold",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "and held to",
          "value" : 0.90000000000000002
        },
        {
          "codeSyntax" : "DesignTokens.Motion.dropRise",
          "name" : "drop-rise",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the drop is up in",
          "value" : 0.5
        },
        {
          "codeSyntax" : "DesignTokens.Motion.dropSpread",
          "name" : "drop-spread",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the bloom reaches its full spread in",
          "value" : 1
        },
        {
          "codeSyntax" : "DesignTokens.Motion.flip",
          "name" : "flip",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the panel's carousel",
          "value" : 0.25
        },
        {
          "codeSyntax" : "DesignTokens.Motion.heightChange",
          "name" : "height-change",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the keyboard resizing",
          "value" : 0.25
        },
        {
          "codeSyntax" : "DesignTokens.Motion.keyPress",
          "name" : "key-press",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "a key lighting",
          "value" : 0.080000000000000002
        },
        {
          "codeSyntax" : "DesignTokens.Motion.mood",
          "name" : "mood",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the orb's colour moving between moods",
          "value" : 0.80000000000000004
        },
        {
          "codeSyntax" : "DesignTokens.Motion.press",
          "name" : "press",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the orb's press; the one thing that answers at once",
          "value" : 0.10000000000000001
        },
        {
          "codeSyntax" : "DesignTokens.Motion.ringPeriod",
          "name" : "ring-period",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "one turn of the ring, the Mac's cadence",
          "value" : 1.6000000000000001
        },
        {
          "codeSyntax" : "DesignTokens.Motion.stateFade",
          "name" : "state-fade",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "every other change on the key: the ring, a glyph, the dimming",
          "value" : 0.5
        },
        {
          "codeSyntax" : "DesignTokens.Motion.termSwap",
          "name" : "term-swap",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the voice bar becoming the field",
          "value" : 0.40000000000000002
        },
        {
          "codeSyntax" : "DesignTokens.Motion.waveFade",
          "name" : "wave-fade",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the orb and the wave crossing, either way",
          "value" : 0.69999999999999996
        }
      ]
    },
    "Themes" : {
      "mode" : "Value",
      "variables" : [
        {
          "alias" : "Brand:ink\/700",
          "codeSyntax" : "DesignTokens.Themes.inkKey",
          "name" : "ink\/key",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#33302A"
        },
        {
          "alias" : "Brand:ink\/800",
          "codeSyntax" : "DesignTokens.Themes.inkKeyModifier",
          "name" : "ink\/key-modifier",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#26231E"
        },
        {
          "alias" : "Brand:warm-white",
          "codeSyntax" : "DesignTokens.Themes.inkLegend",
          "name" : "ink\/legend",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#F2EEE6"
        },
        {
          "alias" : "Brand:ink\/700",
          "codeSyntax" : "DesignTokens.Themes.inkPopup",
          "name" : "ink\/popup",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#33302A"
        },
        {
          "alias" : "Brand:green\/400",
          "codeSyntax" : "DesignTokens.Themes.inkSignal",
          "name" : "ink\/signal",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#67AD82"
        },
        {
          "alias" : "Brand:ink",
          "codeSyntax" : "DesignTokens.Themes.inkSurface",
          "name" : "ink\/surface",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#1D1B16"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.lavenderKey",
          "name" : "lavender\/key",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#3F3777"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.lavenderKeyModifier",
          "name" : "lavender\/key-modifier",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#352E68"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.lavenderLegend",
          "name" : "lavender\/legend",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#F1EEFF"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.lavenderPopup",
          "name" : "lavender\/popup",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#3F3777"
        },
        {
          "alias" : "Brand:green\/400",
          "codeSyntax" : "DesignTokens.Themes.lavenderSignal",
          "name" : "lavender\/signal",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#67AD82"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.lavenderSurface",
          "name" : "lavender\/surface",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#2C2557"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.midnightKey",
          "name" : "midnight\/key",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#1D2440"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.midnightKeyModifier",
          "name" : "midnight\/key-modifier",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#161B33"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.midnightLegend",
          "name" : "midnight\/legend",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#E8ECFF"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.midnightPopup",
          "name" : "midnight\/popup",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#1D2440"
        },
        {
          "alias" : "Brand:green\/400",
          "codeSyntax" : "DesignTokens.Themes.midnightSignal",
          "name" : "midnight\/signal",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#67AD82"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.midnightSurface",
          "name" : "midnight\/surface",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#0E1220"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.mintKey",
          "name" : "mint\/key",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#1E3F31"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.mintKeyModifier",
          "name" : "mint\/key-modifier",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#183429"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.mintLegend",
          "name" : "mint\/legend",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#E9F5EE"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.mintPopup",
          "name" : "mint\/popup",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#1E3F31"
        },
        {
          "alias" : "Brand:green\/400",
          "codeSyntax" : "DesignTokens.Themes.mintSignal",
          "name" : "mint\/signal",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#67AD82"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.mintSurface",
          "name" : "mint\/surface",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#10231B"
        },
        {
          "alias" : "Brand:white",
          "codeSyntax" : "DesignTokens.Themes.paperKey",
          "name" : "paper\/key",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#FFFFFF"
        },
        {
          "alias" : "Brand:card-border",
          "codeSyntax" : "DesignTokens.Themes.paperKeyModifier",
          "name" : "paper\/key-modifier",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#DEDBDB"
        },
        {
          "alias" : "Brand:ink",
          "codeSyntax" : "DesignTokens.Themes.paperLegend",
          "name" : "paper\/legend",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#1D1B16"
        },
        {
          "alias" : "Brand:white",
          "codeSyntax" : "DesignTokens.Themes.paperPopup",
          "name" : "paper\/popup",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#FFFFFF"
        },
        {
          "alias" : "Brand:green\/700",
          "codeSyntax" : "DesignTokens.Themes.paperSignal",
          "name" : "paper\/signal",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#01762F"
        },
        {
          "alias" : "Brand:card",
          "codeSyntax" : "DesignTokens.Themes.paperSurface",
          "name" : "paper\/surface",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#EBE8E8"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.sunsetKey",
          "name" : "sunset\/key",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#4B2B20"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.sunsetKeyModifier",
          "name" : "sunset\/key-modifier",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#3B2119"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.sunsetLegend",
          "name" : "sunset\/legend",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#FFEFE6"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.sunsetPopup",
          "name" : "sunset\/popup",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#4B2B20"
        },
        {
          "alias" : "Brand:green\/400",
          "codeSyntax" : "DesignTokens.Themes.sunsetSignal",
          "name" : "sunset\/signal",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#67AD82"
        },
        {
          "codeSyntax" : "DesignTokens.Themes.sunsetSurface",
          "name" : "sunset\/surface",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#2B1912"
        },
        {
          "alias" : "Brand:apple\/dark-key",
          "codeSyntax" : "DesignTokens.Themes.systemDarkKey",
          "name" : "system-dark\/key",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#6B6B6B"
        },
        {
          "alias" : "Brand:apple\/dark-modifier",
          "codeSyntax" : "DesignTokens.Themes.systemDarkKeyModifier",
          "name" : "system-dark\/key-modifier",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#464646"
        },
        {
          "alias" : "Brand:white",
          "codeSyntax" : "DesignTokens.Themes.systemDarkLegend",
          "name" : "system-dark\/legend",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#FFFFFF"
        },
        {
          "alias" : "Brand:apple\/dark-key",
          "codeSyntax" : "DesignTokens.Themes.systemDarkPopup",
          "name" : "system-dark\/popup",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#6B6B6B"
        },
        {
          "alias" : "Brand:green\/400",
          "codeSyntax" : "DesignTokens.Themes.systemDarkSignal",
          "name" : "system-dark\/signal",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#67AD82"
        },
        {
          "alias" : "Brand:apple\/dark-surface",
          "codeSyntax" : "DesignTokens.Themes.systemDarkSurface",
          "name" : "system-dark\/surface",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#2B2B2B"
        },
        {
          "alias" : "Brand:white",
          "codeSyntax" : "DesignTokens.Themes.systemLightKey",
          "name" : "system-light\/key",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#FFFFFF"
        },
        {
          "alias" : "Brand:apple\/light-modifier",
          "codeSyntax" : "DesignTokens.Themes.systemLightKeyModifier",
          "name" : "system-light\/key-modifier",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#ADB3BC"
        },
        {
          "alias" : "Brand:black",
          "codeSyntax" : "DesignTokens.Themes.systemLightLegend",
          "name" : "system-light\/legend",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#000000"
        },
        {
          "alias" : "Brand:white",
          "codeSyntax" : "DesignTokens.Themes.systemLightPopup",
          "name" : "system-light\/popup",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#FFFFFF"
        },
        {
          "alias" : "Brand:green\/700",
          "codeSyntax" : "DesignTokens.Themes.systemLightSignal",
          "name" : "system-light\/signal",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#01762F"
        },
        {
          "alias" : "Brand:apple\/light-surface",
          "codeSyntax" : "DesignTokens.Themes.systemLightSurface",
          "name" : "system-light\/surface",
          "scopes" : [

          ],
          "type" : "COLOR",
          "use" : "",
          "value" : "#D1D5DB"
        }
      ]
    },
    "Typography" : {
      "mode" : "Value",
      "variables" : [
        {
          "codeSyntax" : "DesignTokens.Typography.ratioOrbGlyph",
          "name" : "ratio\/orb-glyph",
          "scopes" : [

          ],
          "type" : "FLOAT",
          "use" : "the clipboard and exclamation glyphs, as a fraction of the orb",
          "value" : 0.34000000000000002
        },
        {
          "codeSyntax" : "DesignTokens.Typography.sizeGlyph",
          "name" : "size\/glyph",
          "scopes" : [
            "FONT_SIZE"
          ],
          "type" : "FLOAT",
          "use" : "the +, × and ✓",
          "value" : 17
        },
        {
          "codeSyntax" : "DesignTokens.Typography.sizeLegend",
          "name" : "size\/legend",
          "scopes" : [
            "FONT_SIZE"
          ],
          "type" : "FLOAT",
          "use" : "every other key",
          "value" : 16
        },
        {
          "codeSyntax" : "DesignTokens.Typography.sizeLetter",
          "name" : "size\/letter",
          "scopes" : [
            "FONT_SIZE"
          ],
          "type" : "FLOAT",
          "use" : "letter keys",
          "value" : 22
        },
        {
          "codeSyntax" : "DesignTokens.Typography.sizePopup",
          "name" : "size\/popup",
          "scopes" : [
            "FONT_SIZE"
          ],
          "type" : "FLOAT",
          "use" : "the letter pop-up",
          "value" : 32
        },
        {
          "codeSyntax" : "DesignTokens.Typography.sizeTerm",
          "name" : "size\/term",
          "scopes" : [
            "FONT_SIZE"
          ],
          "type" : "FLOAT",
          "use" : "the key-term field",
          "value" : 17
        },
        {
          "codeSyntax" : "DesignTokens.Typography.weightGlyph",
          "name" : "weight\/glyph",
          "scopes" : [
            "FONT_STYLE"
          ],
          "type" : "STRING",
          "use" : "",
          "value" : "medium"
        },
        {
          "codeSyntax" : "DesignTokens.Typography.weightLegend",
          "name" : "weight\/legend",
          "scopes" : [
            "FONT_STYLE"
          ],
          "type" : "STRING",
          "use" : "",
          "value" : "medium"
        },
        {
          "codeSyntax" : "DesignTokens.Typography.weightLetter",
          "name" : "weight\/letter",
          "scopes" : [
            "FONT_STYLE"
          ],
          "type" : "STRING",
          "use" : "",
          "value" : "regular"
        },
        {
          "codeSyntax" : "DesignTokens.Typography.weightOrbGlyph",
          "name" : "weight\/orb-glyph",
          "scopes" : [
            "FONT_STYLE"
          ],
          "type" : "STRING",
          "use" : "",
          "value" : "semibold"
        },
        {
          "codeSyntax" : "DesignTokens.Typography.weightPopup",
          "name" : "weight\/popup",
          "scopes" : [
            "FONT_STYLE"
          ],
          "type" : "STRING",
          "use" : "",
          "value" : "regular"
        },
        {
          "codeSyntax" : "DesignTokens.Typography.weightTerm",
          "name" : "weight\/term",
          "scopes" : [
            "FONT_STYLE"
          ],
          "type" : "STRING",
          "use" : "",
          "value" : "regular"
        }
      ]
    }
  },
  "gradients" : {
    "orb" : {
      "end" : "top",
      "start" : "bottom",
      "stops" : [
        {
          "alias" : "Brand:violet\/lavender",
          "location" : 0,
          "value" : "#D7D3F4"
        },
        {
          "alias" : "Brand:violet\/periwinkle",
          "location" : 0.067299999999999999,
          "value" : "#B0A7E9"
        },
        {
          "alias" : "Brand:green\/400",
          "location" : 0.14419999999999999,
          "value" : "#67AD82"
        },
        {
          "alias" : "Brand:green\/700",
          "location" : 0.3029,
          "value" : "#01762F"
        },
        {
          "alias" : "Brand:cobolt",
          "location" : 0.59619999999999995,
          "value" : "#3923C7"
        },
        {
          "alias" : "Brand:violet\/iris",
          "location" : 0.75,
          "value" : "#887BDD"
        },
        {
          "alias" : "Brand:violet\/lavender",
          "location" : 0.89419999999999999,
          "value" : "#D7D3F4"
        },
        {
          "alias" : "Brand:white",
          "location" : 1,
          "value" : "#FFFFFF"
        }
      ],
      "use" : "the Mac orb's fill, the design's own stops (App elements\/Recording.svg), swept bottom to top"
    },
    "orb-ring" : {
      "end" : "bottomTrailing",
      "start" : "topLeading",
      "stops" : [
        {
          "alias" : "Brand:green\/700",
          "location" : 0,
          "value" : "#01762F"
        },
        {
          "alias" : "Brand:white",
          "location" : 1,
          "value" : "#FFFFFF"
        }
      ],
      "use" : "the ring round the orb: green into white, corner to corner; spun while something is happening"
    }
  },
  "groups" : [
    "Brand",
    "Themes",
    "Keyboard",
    "Metrics",
    "Typography",
    "Motion"
  ]
};
