#!/bin/bash
# Fan the design tokens out, or prove they already are.
#
#   scripts/design-sync.sh          # regenerate DesignTokens.swift, DESIGN.md's tables, the colour sets
#   scripts/design-sync.sh --check  # regenerate into .build/ and diff; non-zero on drift
#
# `App/BlurtiOS/Design/tokens.json` is the one source for the keyboard's colours
# and numbers (exported from the Figma file — see DESIGN.md › Figma). Everything
# that repeats a value from it is generated by scripts/design-tokens.swift, and
# check.sh runs `--check` so a hand edit to a generated file, or a token change
# without a regeneration, fails the way a stale .pbxproj does.
#
# Both modes also lint the keyboard's view files for design literals: a number
# inside a layout or motion modifier that isn't 0 or 1 belongs in tokens.json,
# not in the view. End the line with `// literal-ok: <reason>` when it is
# genuinely local (a divide-by-two, a geometry derivation).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

CHECK=0
if [ "${1:-}" = "--check" ]; then
  CHECK=1
elif [ -n "${1:-}" ]; then
  echo "usage: scripts/design-sync.sh [--check]" >&2
  exit 2
fi

if command -v xcrun >/dev/null 2>&1 && xcrun --find swift-format >/dev/null 2>&1; then
  SWIFT_FORMAT=(xcrun swift-format)
elif command -v swift-format >/dev/null 2>&1; then
  SWIFT_FORMAT=(swift-format)
else
  SWIFT_FORMAT=()
fi

OUTPUTS=(
  App/BlurtiOS/Shared/DesignTokens.swift
  App/BlurtiOS/DESIGN.md
  App/BlurtiOS/BlurtiOS/Assets.xcassets/AccentColor.colorset/Contents.json
  App/BlurtiOS/BlurtiOS/Assets.xcassets/CardFill.colorset/Contents.json
  App/BlurtiOS/BlurtiOS/Assets.xcassets/CardBorder.colorset/Contents.json
  App/BlurtiOS/BlurtiOS/Assets.xcassets/Page.colorset/Contents.json
  App/BlurtiOS/BlurtiOS/Assets.xcassets/Text.colorset/Contents.json
  App/BlurtiOS/BlurtiOS/Assets.xcassets/Muted.colorset/Contents.json
  App/BlurtiOS/BlurtiOS/Assets.xcassets/CTA.colorset/Contents.json
  App/BlurtiOS/BlurtiOS/Assets.xcassets/CTAText.colorset/Contents.json
  App/BlurtiOS/Design/figma/tokens.js
)

# Format the generated files the way check.sh expects the tree to be formatted,
# so a regeneration never fails swift-format or prettier on its own output.
# `--ignore-path /dev/null`: .prettierignore excludes .build/, where --check
# writes, and an explicitly named ignored file is skipped, not formatted.
format_outputs() {
  local root="$1"
  if [ "${#SWIFT_FORMAT[@]}" -gt 0 ]; then
    "${SWIFT_FORMAT[@]}" format --in-place "$root/App/BlurtiOS/Shared/DesignTokens.swift"
  fi
  if command -v prettier >/dev/null 2>&1; then
    prettier --log-level warn --ignore-path /dev/null --write "$root/App/BlurtiOS/DESIGN.md" >/dev/null
  fi
}

# The design-literal lint. Scope: every file under the keyboard's and the
# app's sources that draws — new views are linted by default — minus the few
# that compute rather than draw (the host controller, the palette, the
# geometry) and Grain.swift, whose body is the grain's recipe (density,
# the two shades), with only its opacity as a token. Numbers 0 and 1 pass: `Spacer(minLength: 0)`,
# `.opacity(on ? 1 : 0)` and `scaleEffect(1 + …)` are structure, not design.
lint_literals() {
  python3 - <<'PY'
import glob, os, re, sys
# BlurtiOSCore (the model, the voice state, the interaction rules) is not
# globbed at all: it draws nothing, so it has no design literals to carry.
exempt = {
    "KeyboardViewController.swift", "KeyboardPalette.swift", "KeyGeometry.swift", "MotionHeld.swift", "Grain.swift",
}
app_exempt = {
    "BlurtiOSApp.swift", "DictationCoordinator.swift", "ListeningWindow.swift", "ListeningSource.swift",
    "AudioSource.swift", "SimulatorAudioSource.swift", "KeyboardGalleryView.swift", "KeyboardProbeView.swift",
}
files = sorted(
    [path for path in glob.glob("App/BlurtiOS/BlurtKeyboard/Sources/**/*.swift", recursive=True)
     if os.path.basename(path) not in exempt]
    + [path for path in glob.glob("App/BlurtiOS/BlurtiOS/Sources/*.swift") if os.path.basename(path) not in app_exempt]
)
modifiers = re.compile(
    r"\.(padding|frame|font|blur|scaleEffect|offset|shadow|opacity|cornerRadius|saturation|brightness"
    r"|strokeBorder|stroke|lineWidth)\(|\b(spacing|duration|minimumDistance|lineWidth|radius|size|width|height|by):"
)
number = re.compile(r"(?<![\w.])(\d+(?:\.\d+)?)(?![\w.])")
bad = []
for path in files:
    for lineno, line in enumerate(open(path, encoding="utf-8"), 1):
        code = re.sub(r'"(?:[^"\\]|\\.)*"', '""', line.split("//")[0])
        if "literal-ok:" in line or not modifiers.search(code):
            continue
        hits = [n for n in number.findall(code) if n not in ("0", "1")]
        if hits:
            bad.append(f"{path}:{lineno}: {', '.join(hits)} — {line.strip()}")
if bad:
    print("design-sync: design literals in views; move them to App/BlurtiOS/Design/tokens.json", file=sys.stderr)
    for b in bad:
        print("  " + b, file=sys.stderr)
    sys.exit(1)
print(f"design-sync: no design literals in {len(files)} view files")
PY
}

# The Figma development-plugin bundle: the same scripts a use_figma call
# carries, concatenated behind a manifest, for running from Figma desktop
# without the MCP read quota (Design/figma/README.md).
bundle_plugin() {
  local dir="$REPO_ROOT/.build/figma-plugin"
  mkdir -p "$dir"
  cp App/BlurtiOS/Design/figma/manifest.json "$dir/manifest.json"
  (
    cd App/BlurtiOS/Design/figma \
      && cat tokens.js core.js foundations.js components.js layouts.js themes.js exports.js plugin.js
  ) >"$dir/code.js"
  echo "design-sync: Figma plugin bundled at $dir (Plugins → Development → Import plugin from manifest)"
}

if [ "$CHECK" -eq 0 ]; then
  swift scripts/design-tokens.swift
  format_outputs "$REPO_ROOT"
  lint_literals
  bundle_plugin
  exit 0
fi

STAGE="$REPO_ROOT/.build/design-sync"
rm -rf "$STAGE"
mkdir -p "$STAGE"
swift scripts/design-tokens.swift --root "$STAGE" >/dev/null
format_outputs "$STAGE"
DRIFT=0
for file in "${OUTPUTS[@]}"; do
  if ! diff -u "$file" "$STAGE/$file" >"$STAGE/diff.txt" 2>&1; then
    echo "error: $file is out of sync with App/BlurtiOS/Design/tokens.json:" >&2
    head -40 "$STAGE/diff.txt" >&2
    DRIFT=1
  fi
done
if [ "$DRIFT" -ne 0 ]; then
  echo "       run scripts/design-sync.sh and commit the result" >&2
  exit 1
fi
echo "design-sync: ${#OUTPUTS[@]} generated files match tokens.json"
lint_literals
