// Generated by scripts/design-tokens.swift from App/BlurtiOS/Design/tokens.json — do not edit.
// Regenerate with scripts/design-sync.sh; scripts/check.sh fails on drift.
// periphery:ignore:all
// swiftlint:disable file_length
import SwiftUI

// swiftlint:disable type_body_length
/// The design's colours and numbers, from the one source Figma exports
/// (`Design/tokens.json`): what the views draw with, what DESIGN.md's tables
/// say, and what the asset catalog holds, all from the same file. Swift names
/// follow the token names by one rule (`kb/key-modifier` → `kbKeyModifier`),
/// the same rule the Figma build script uses for iOS code syntax.
enum DesignTokens {
  enum Brand {
    /// The iPhone keyboard's dark key.
    nonisolated static let appleDarkKey: Color = Color(hex: 0x6B6B6B)
    /// The iPhone keyboard's dark modifier key.
    nonisolated static let appleDarkModifier: Color = Color(hex: 0x464646)
    /// The iPhone keyboard's dark surface.
    nonisolated static let appleDarkSurface: Color = Color(hex: 0x2B2B2B)
    /// The iPhone keyboard's light modifier key.
    nonisolated static let appleLightModifier: Color = Color(hex: 0xADB3BC)
    /// The iPhone keyboard's light surface.
    nonisolated static let appleLightSurface: Color = Color(hex: 0xD1D5DB)
    nonisolated static let black: Color = Color(hex: 0x000000)
    /// The warm card fill; the paper theme's surface.
    nonisolated static let card: Color = Color(hex: 0xEBE8E8)
    /// The card's hairline; the paper theme's modifier key.
    nonisolated static let cardBorder: Color = Color(hex: 0xDEDBDB)
    /// AssemblyAI's primary violet: the drop, never a key or a surface.
    nonisolated static let cobolt: Color = Color(hex: 0x3923C7)
    /// The design system's UI-and-code green fill (unused on the phone yet).
    nonisolated static let green100: Color = Color(hex: 0xCCE4D5)
    /// The design system's UI-and-code green highlight (unused on the phone yet).
    nonisolated static let green200: Color = Color(hex: 0x99C8AC)
    /// The brand hue lifted for dark chrome: the meter, the ring, the wave on ink.
    nonisolated static let green400: Color = Color(hex: 0x67AD82)
    /// The wordmark green, light chrome (the app's accent in light).
    nonisolated static let green700: Color = Color(hex: 0x01762F)
    /// The pale green the orb lightens into.
    nonisolated static let greenMist: Color = Color(hex: 0xDBF5E6)
    /// The brand ink: the Mac pill's body, the ink theme's surface.
    nonisolated static let ink: Color = Color(hex: 0x1D1B16)
    /// The Mac's dark card border.
    nonisolated static let ink600: Color = Color(hex: 0x3A362F)
    /// An ordinary key on ink, one step up.
    nonisolated static let ink700: Color = Color(hex: 0x33302A)
    /// A modifier key on ink; the Mac's dark card fill.
    nonisolated static let ink800: Color = Color(hex: 0x26231E)
    /// Black-100: the lightest warm grey.
    nonisolated static let neutral300: Color = Color(hex: 0xD2D1D0)
    /// Black-200: mono labels on the dark face.
    nonisolated static let neutral500: Color = Color(hex: 0xA5A4A2)
    /// Black-300: muted text and mono labels on the light face.
    nonisolated static let neutral700: Color = Color(hex: 0x777673)
    /// Black-400: body text on the light face.
    nonisolated static let neutral900: Color = Color(hex: 0x4A4945)
    /// The error word and ring, cancel, the Full Access note; never a red body.
    nonisolated static let orange: Color = Color(hex: 0xE67F36)
    /// Neutral-100: the light face's surface.
    nonisolated static let paper200: Color = Color(hex: 0xECEBE5)
    /// Neutral-200: a modifier key on the light face.
    nonisolated static let paper300: Color = Color(hex: 0xDAD7CB)
    /// Neutral-300: hairlines and field borders on the light face.
    nonisolated static let paper400: Color = Color(hex: 0xC7C3B2)
    /// The design system's page: the app's light ground.
    nonisolated static let paperPage: Color = Color(hex: 0xFDFCF8)
    /// The warm off-white one step in: light cards, dark legends.
    nonisolated static let paperTint: Color = Color(hex: 0xF5F3EB)
    /// The orb gradient's upper violet stop.
    nonisolated static let violetIris: Color = Color(hex: 0x887BDD)
    /// The orb's lightest violet: its top and the gradient's ends.
    nonisolated static let violetLavender: Color = Color(hex: 0xD7D3F4)
    /// The orb's mid violet: the drop's halo.
    nonisolated static let violetPeriwinkle: Color = Color(hex: 0xB0A7E9)
    /// Key legends on ink: warm white on warm ink.
    nonisolated static let warmWhite: Color = Color(hex: 0xF2EEE6)
    nonisolated static let white: Color = Color(hex: 0xFFFFFF)
  }

  enum Themes {
    /// `brand.ink/700`.
    nonisolated static let darkField: Color = Brand.ink700
    /// `brand.ink/600`.
    nonisolated static let darkFieldBorder: Color = Brand.ink600
    /// `brand.ink/700`.
    nonisolated static let darkKey: Color = Brand.ink700
    /// `brand.ink/800`.
    nonisolated static let darkKeyModifier: Color = Brand.ink800
    /// `brand.paper/tint`.
    nonisolated static let darkLegend: Color = Brand.paperTint
    /// `brand.neutral/500`.
    nonisolated static let darkLegendSecondary: Color = Brand.neutral500
    /// `brand.orange`.
    nonisolated static let darkNotice: Color = Brand.orange
    /// `brand.ink/700`.
    nonisolated static let darkPopup: Color = Brand.ink700
    /// `brand.green/400`.
    nonisolated static let darkSignal: Color = Brand.green400
    /// `brand.ink`.
    nonisolated static let darkSurface: Color = Brand.ink
    /// `brand.white`.
    nonisolated static let lightField: Color = Brand.white
    /// `brand.paper/400`.
    nonisolated static let lightFieldBorder: Color = Brand.paper400
    /// `brand.white`.
    nonisolated static let lightKey: Color = Brand.white
    /// `brand.paper/300`.
    nonisolated static let lightKeyModifier: Color = Brand.paper300
    /// `brand.ink`.
    nonisolated static let lightLegend: Color = Brand.ink
    /// `brand.neutral/700`.
    nonisolated static let lightLegendSecondary: Color = Brand.neutral700
    /// `brand.orange`.
    nonisolated static let lightNotice: Color = Brand.orange
    /// `brand.white`.
    nonisolated static let lightPopup: Color = Brand.white
    /// `brand.green/700`.
    nonisolated static let lightSignal: Color = Brand.green700
    /// `brand.paper/200`.
    nonisolated static let lightSurface: Color = Brand.paper200
  }

  enum Keyboard {
    /// The catalog's AccentColor in dark.
    nonisolated static let appAccentDark: Color = Brand.green400
    /// The catalog's AccentColor in light.
    nonisolated static let appAccentLight: Color = Brand.green700
    /// The catalog's CardBorder in dark.
    nonisolated static let appCardBorderDark: Color = Brand.ink600
    /// The catalog's CardBorder in light.
    nonisolated static let appCardBorderLight: Color = Brand.paper400
    /// The catalog's CardFill in dark.
    nonisolated static let appCardFillDark: Color = Brand.ink800
    /// The catalog's CardFill in light.
    nonisolated static let appCardFillLight: Color = Brand.paperTint
    /// The panel's cancel ×.
    nonisolated static let kbCancel: Color = Brand.orange
    /// The key-term field.
    nonisolated static let kbField: Color = Themes.darkField
    /// The field's hairline.
    nonisolated static let kbFieldBorder: Color = Themes.darkFieldBorder
    /// The one line of words the keyboard ever shows.
    nonisolated static let kbFullAccessNote: Color = Brand.orange
    /// An ordinary key.
    nonisolated static let kbKey: Color = Themes.darkKey
    /// Shift, delete, globe, return, 123, cancel.
    nonisolated static let kbKeyModifier: Color = Themes.darkKeyModifier
    /// Key legends and bare glyphs.
    nonisolated static let kbLegend: Color = Themes.darkLegend
    /// The mono word labels (123, ABC, return, space) and the + at rest.
    nonisolated static let kbLegendSecondary: Color = Themes.darkLegendSecondary
    /// The solid ring and glyph for an error.
    nonisolated static let kbNoticeError: Color = Brand.orange
    /// The solid ring for pasted and copied.
    nonisolated static let kbNoticeOk: Color = Brand.green400
    /// The sweeping ring's gradient, bottom-trailing.
    nonisolated static let kbOrbRingEnd: Color = Brand.white
    /// The sweeping ring's gradient, top-leading.
    nonisolated static let kbOrbRingStart: Color = Brand.green700
    /// The letter pop-up.
    nonisolated static let kbPopup: Color = Themes.darkPopup
    /// The wave, the caret, the saved check.
    nonisolated static let kbSignal: Color = Themes.darkSignal
    /// The design face's surface (Figma binds to kb/*; Swift reads the palette).
    nonisolated static let kbSurface: Color = Themes.darkSurface
  }

  enum Metrics {
    /// The + from the panel's corner.
    nonisolated static let addtermInset: CGFloat = 6
    /// The card's hairline.
    nonisolated static let cardBorder: CGFloat = 1
    /// The app's cards.
    nonisolated static let cardRadius: CGFloat = 16
    nonisolated static let caretHeight: CGFloat = 20
    /// The caret's gap from the text.
    nonisolated static let caretLead: CGFloat = 1
    nonisolated static let caretRadius: CGFloat = 1
    nonisolated static let caretWidth: CGFloat = 2
    /// The carousel gesture's minimum distance.
    nonisolated static let gestureSwipeMin: CGFloat = 24
    /// The +, × and ✓ touch targets.
    nonisolated static let glyphHit: CGFloat = 32
    /// Between keys, the iPhone's.
    nonisolated static let keyGap: CGFloat = 6
    /// Every key.
    nonisolated static let keyHeight: CGFloat = 42
    /// A letter key at 402 pt (iPhone 18 Pro): (width − 9 × key/gap) / 10.
    nonisolated static let keyLetterWidth402: CGFloat = 34.8
    /// A key that isn't given a width.
    nonisolated static let keyMinWidth: CGFloat = 44
    /// A legend's side padding on a min-width key.
    nonisolated static let keyPad: CGFloat = 4
    /// Flat keys, one colour at this corner.
    nonisolated static let keyRadius: CGFloat = 8
    /// Return at 402 pt: two side keys and a gap.
    nonisolated static let keyReturnWidth402: CGFloat = 104.4
    /// Shift and delete stand this many key gaps from the letters.
    nonisolated static let keySideGapFactor: CGFloat = 2
    /// Shift, delete, 123 and globe at 402 pt: what seven letters leave, halved.
    nonisolated static let keySideWidth402: CGFloat = 49.2
    /// 2 × margin/vertical + voicebar/height + 4 × row/gap + 4 × key/height.
    nonisolated static let layoutFull: CGFloat = 272
    /// Chosen: room for the 96 orb over one key row.
    nonisolated static let layoutPanel: CGFloat = 216
    /// 2 × margin/vertical + voicebar/height.
    nonisolated static let layoutSlim: CGFloat = 60
    /// At the keyboard's sides.
    nonisolated static let marginSide: CGFloat = 3
    /// The keyboard's top and bottom.
    nonisolated static let marginVertical: CGFloat = 8
    /// The orb when Blurt isn't ready.
    nonisolated static let opacityDim: CGFloat = 0.8
    /// And its saturation.
    nonisolated static let opacityDimSaturation: CGFloat = 0.35
    /// The + without Full Access.
    nonisolated static let opacityDisabled: CGFloat = 0.4
    nonisolated static let opacityGrain: CGFloat = 0.5
    /// The home hero's saturation when not listening.
    nonisolated static let opacityHomeDimSaturation: CGFloat = 0.45
    /// Key legends over the cap; below 1 they sit back.
    nonisolated static let opacityLegend: CGFloat = 1
    /// The + at rest.
    nonisolated static let opacityLegendMuted: CGFloat = 0.5
    nonisolated static let opacityOrbLight: CGFloat = 0.3
    /// The field's placeholder.
    nonisolated static let opacityPlaceholder: CGFloat = 0.4
    nonisolated static let opacityPopupShadow: CGFloat = 0.12
    /// A key lightens this much while pressed.
    nonisolated static let opacityPressBrighten: CGFloat = 0.15
    /// Film grain over the whole keyboard surface: matte, the brand's texture.
    nonisolated static let opacitySurfaceGrain: CGFloat = 0.14
    /// A soft darkening toward the surface's edges; 0 is none.
    nonisolated static let opacitySurfaceVignette: CGFloat = 0
    /// The field's ×.
    nonisolated static let opacityTermCancel: CGFloat = 0.7
    /// The orb in the voice bar.
    nonisolated static let orbBar: CGFloat = 40
    /// And blurs to this fraction of its size.
    nonisolated static let orbDissipateBlur: CGFloat = 0.16
    /// The orb swells to this while dissipating.
    nonisolated static let orbDissipateScale: CGFloat = 1.25
    /// The orb on the home screen.
    nonisolated static let orbHome: CGFloat = 112
    /// The soft light's reach, as a fraction of the orb (was a fixed 110 pt, flat on a 40 pt orb).
    nonisolated static let orbLightReach: CGFloat = 0.9
    /// The soft light's centre, as a fraction of the orb.
    nonisolated static let orbLightX: CGFloat = 0.3
    nonisolated static let orbLightY: CGFloat = 0.22
    /// The orb in the panel.
    nonisolated static let orbPanel: CGFloat = 96
    /// Between the panel's orb and its key row.
    nonisolated static let panelSpacing: CGFloat = 12
    /// The theme card draws the keyboard at this width.
    nonisolated static let pickerPreviewWidth: CGFloat = 393
    /// The theme card's preview corners.
    nonisolated static let pickerRadius: CGFloat = 10
    /// Then scales it to fit two across.
    nonisolated static let pickerScale: CGFloat = 0.42
    /// The letter pop-up is the key width plus this.
    nonisolated static let popupExtraWidth: CGFloat = 18
    nonisolated static let popupHeight: CGFloat = 56
    /// The pop-up sits this far above the key.
    nonisolated static let popupOffset: CGFloat = 58
    nonisolated static let popupRadius: CGFloat = 10
    /// The one thing that floats.
    nonisolated static let popupShadowRadius: CGFloat = 8
    nonisolated static let popupShadowY: CGFloat = 2
    /// The orb while pressed.
    nonisolated static let pressScale: CGFloat = 0.94
    /// The ring while working or noticing; the home ring.
    nonisolated static let ringActive: CGFloat = 2
    /// The ring at rest.
    nonisolated static let ringStill: CGFloat = 1
    /// Between rows, the iPhone's.
    nonisolated static let rowGap: CGFloat = 11
    /// Between the slim bar's keys.
    nonisolated static let slimSpacing: CGFloat = 8
    /// Where it is full.
    nonisolated static let surfaceVignetteEnd: CGFloat = 0.75
    /// Where the vignette begins, as a fraction of the keyboard's width.
    nonisolated static let surfaceVignetteStart: CGFloat = 0.3
    /// × · field · ✓.
    nonisolated static let termGap: CGFloat = 8
    /// The key-term field's capsule.
    nonisolated static let termHeight: CGFloat = 36
    /// The field row's side inset.
    nonisolated static let termInset: CGFloat = 2
    /// The field's side padding.
    nonisolated static let termPad: CGFloat = 14
    /// The wave stays this clear of the + at the trailing edge.
    nonisolated static let voicebarAddtermClearance: CGFloat = 12
    /// The voice row, where the system puts its suggestion bar.
    nonisolated static let voicebarHeight: CGFloat = 44
    /// Between the orb and the Full Access note.
    nonisolated static let voicebarNoteGap: CGFloat = 10
    /// A wave bar's width.
    nonisolated static let waveBar: CGFloat = 2
    nonisolated static let waveBarHeight: CGFloat = 24
    /// The wave in the voice bar, at most.
    nonisolated static let waveBarWidth: CGFloat = 240
    /// Between wave bars.
    nonisolated static let waveGap: CGFloat = 2
    nonisolated static let waveHomeHeight: CGFloat = 44
    nonisolated static let waveHomeWidth: CGFloat = 280
    /// 1 draws the wave as one liquid shape through the bar heights instead of the bars themselves.
    nonisolated static let waveLiquid: CGFloat = 0
    nonisolated static let wavePanelHeight: CGFloat = 40
    nonisolated static let wavePanelWidth: CGFloat = 300
    nonisolated static let wordmarkHeight: CGFloat = 22
  }

  enum Typography {
    /// The clipboard and exclamation glyphs, as a fraction of the orb.
    nonisolated static let ratioOrbGlyph: CGFloat = 0.34
    /// The app's body text.
    nonisolated static let sizeBody: CGFloat = 16
    /// The app's small text.
    nonisolated static let sizeCaption: CGFloat = 14
    /// A mono button label in the app (E2).
    nonisolated static let sizeCta: CGFloat = 14
    /// A mono eyebrow in the app (E1).
    nonisolated static let sizeEyebrow: CGFloat = 12
    /// The +, × and ✓.
    nonisolated static let sizeGlyph: CGFloat = 17
    /// The mono word labels on keys: 123, ABC, #+=, space, the return label.
    nonisolated static let sizeLabel: CGFloat = 12
    /// Every other key.
    nonisolated static let sizeLegend: CGFloat = 16
    /// Letter keys.
    nonisolated static let sizeLetter: CGFloat = 22
    /// The letter pop-up.
    nonisolated static let sizePopup: CGFloat = 32
    /// The key-term field.
    nonisolated static let sizeTerm: CGFloat = 17
    /// The app's serif headline.
    nonisolated static let sizeTitle: CGFloat = 34
    /// Uppercase mono at 14: the brand's E2 tracking.
    nonisolated static let trackingCta: CGFloat = 1.4
    /// Uppercase mono at 12: the brand's E1 tracking.
    nonisolated static let trackingEyebrow: CGFloat = 1.2
    nonisolated static let weightGlyph: Font.Weight = .medium
    nonisolated static let weightLabel: Font.Weight = .medium
    nonisolated static let weightLegend: Font.Weight = .medium
    nonisolated static let weightLetter: Font.Weight = .regular
    nonisolated static let weightOrbGlyph: Font.Weight = .semibold
    nonisolated static let weightPopup: Font.Weight = .regular
    nonisolated static let weightTerm: Font.Weight = .regular
  }

  enum Motion {
    /// The caret's blink.
    nonisolated static let caret: Double = 0.5
    /// A colour or fill changing state: the brand's transition.
    nonisolated static let colour: Double = 0.2
    /// The violet drop is gone by.
    nonisolated static let drop: Double = 2.4
    /// And held to.
    nonisolated static let dropHold: Double = 0.9
    /// The drop is up in.
    nonisolated static let dropRise: Double = 0.5
    /// The bloom reaches its full spread in.
    nonisolated static let dropSpread: Double = 1
    /// The house curve for everything that moves; nothing springs.
    nonisolated static let easeSignature: UnitCurve = UnitCurve.bezier(
      startControlPoint: UnitPoint(x: 0.22, y: 1), endControlPoint: UnitPoint(x: 0.36, y: 1))
    /// The panel's carousel.
    nonisolated static let flip: Double = 0.25
    /// The keyboard resizing.
    nonisolated static let heightChange: Double = 0.25
    /// A key lighting.
    nonisolated static let keyPress: Double = 0.08
    /// The glint when the words land.
    nonisolated static let landing: Double = 0.6
    /// The orb's colour moving between moods.
    nonisolated static let mood: Double = 0.8
    /// The orb's press; the one thing that answers at once.
    nonisolated static let press: Double = 0.1
    /// One turn of the ring, the Mac's cadence.
    nonisolated static let ringPeriod: Double = 1.6
    /// Every other change on the key: the ring, a glyph, the dimming.
    nonisolated static let stateFade: Double = 0.5
    /// The voice bar becoming the field.
    nonisolated static let termSwap: Double = 0.4
    /// The orb and the wave crossing, either way.
    nonisolated static let waveFade: Double = 0.7
  }

  enum Fonts {
    nonisolated static let bodyBold: String = "UN-11ST-Bold"
    /// The app's body text.
    nonisolated static let bodyFamily: String = "UN-11 ST"
    nonisolated static let bodyRegular: String = "UN-11ST-Regular"
    /// The app's serif headlines, sentence case, tight.
    nonisolated static let headingFamily: String = "Oceanic Text"
    nonisolated static let headingRegular: String = "OceanicText-Regular"
    /// Eyebrows, CTAs, the keyboard's word labels.
    nonisolated static let monoFamily: String = "Modern Gothic Mono"
    nonisolated static let monoLight: String = "ModernGothicMono-Light"
    nonisolated static let monoMedium: String = "ModernGothicMono-Medium"
    nonisolated static let monoRegular: String = "ModernGothicMono-Regular"
  }

  enum Gradients {
    /// The Mac orb's fill, the design's own stops (App elements/Recording.svg), swept bottom to top.
    nonisolated static let orb = LinearGradient(
      stops: [
        .init(color: Brand.violetLavender, location: 0),
        .init(color: Brand.violetPeriwinkle, location: 0.0673),
        .init(color: Brand.green400, location: 0.1442),
        .init(color: Brand.green700, location: 0.3029),
        .init(color: Brand.cobolt, location: 0.5962),
        .init(color: Brand.violetIris, location: 0.75),
        .init(color: Brand.violetLavender, location: 0.8942),
        .init(color: Brand.white, location: 1),
      ],
      startPoint: .bottom, endPoint: .top)
    /// The ring round the orb: green into white, corner to corner; spun while something is happening.
    nonisolated static let orbRing = LinearGradient(
      stops: [
        .init(color: Brand.green700, location: 0),
        .init(color: Brand.white, location: 1),
      ],
      startPoint: .topLeading, endPoint: .bottomTrailing)
  }

  /// Every token as `group.name: value`, the way tokens.json renders it, so a
  /// test can pin the compiled values to the file (`DesignTokensTests`).
  nonisolated static let manifest: [String: String] = [
    "brand.apple/dark-key": "#6B6B6B",
    "brand.apple/dark-modifier": "#464646",
    "brand.apple/dark-surface": "#2B2B2B",
    "brand.apple/light-modifier": "#ADB3BC",
    "brand.apple/light-surface": "#D1D5DB",
    "brand.black": "#000000",
    "brand.card": "#EBE8E8",
    "brand.card-border": "#DEDBDB",
    "brand.cobolt": "#3923C7",
    "brand.green/100": "#CCE4D5",
    "brand.green/200": "#99C8AC",
    "brand.green/400": "#67AD82",
    "brand.green/700": "#01762F",
    "brand.green/mist": "#DBF5E6",
    "brand.ink": "#1D1B16",
    "brand.ink/600": "#3A362F",
    "brand.ink/700": "#33302A",
    "brand.ink/800": "#26231E",
    "brand.neutral/300": "#D2D1D0",
    "brand.neutral/500": "#A5A4A2",
    "brand.neutral/700": "#777673",
    "brand.neutral/900": "#4A4945",
    "brand.orange": "#E67F36",
    "brand.paper/200": "#ECEBE5",
    "brand.paper/300": "#DAD7CB",
    "brand.paper/400": "#C7C3B2",
    "brand.paper/page": "#FDFCF8",
    "brand.paper/tint": "#F5F3EB",
    "brand.violet/iris": "#887BDD",
    "brand.violet/lavender": "#D7D3F4",
    "brand.violet/periwinkle": "#B0A7E9",
    "brand.warm-white": "#F2EEE6",
    "brand.white": "#FFFFFF",
    "themes.dark/field": "#33302A",
    "themes.dark/field-border": "#3A362F",
    "themes.dark/key": "#33302A",
    "themes.dark/key-modifier": "#26231E",
    "themes.dark/legend": "#F5F3EB",
    "themes.dark/legend-secondary": "#A5A4A2",
    "themes.dark/notice": "#E67F36",
    "themes.dark/popup": "#33302A",
    "themes.dark/signal": "#67AD82",
    "themes.dark/surface": "#1D1B16",
    "themes.light/field": "#FFFFFF",
    "themes.light/field-border": "#C7C3B2",
    "themes.light/key": "#FFFFFF",
    "themes.light/key-modifier": "#DAD7CB",
    "themes.light/legend": "#1D1B16",
    "themes.light/legend-secondary": "#777673",
    "themes.light/notice": "#E67F36",
    "themes.light/popup": "#FFFFFF",
    "themes.light/signal": "#01762F",
    "themes.light/surface": "#ECEBE5",
    "keyboard.app/accent-dark": "#67AD82",
    "keyboard.app/accent-light": "#01762F",
    "keyboard.app/card-border-dark": "#3A362F",
    "keyboard.app/card-border-light": "#C7C3B2",
    "keyboard.app/card-fill-dark": "#26231E",
    "keyboard.app/card-fill-light": "#F5F3EB",
    "keyboard.kb/cancel": "#E67F36",
    "keyboard.kb/field": "#33302A",
    "keyboard.kb/field-border": "#3A362F",
    "keyboard.kb/full-access-note": "#E67F36",
    "keyboard.kb/key": "#33302A",
    "keyboard.kb/key-modifier": "#26231E",
    "keyboard.kb/legend": "#F5F3EB",
    "keyboard.kb/legend-secondary": "#A5A4A2",
    "keyboard.kb/notice-error": "#E67F36",
    "keyboard.kb/notice-ok": "#67AD82",
    "keyboard.kb/orb-ring-end": "#FFFFFF",
    "keyboard.kb/orb-ring-start": "#01762F",
    "keyboard.kb/popup": "#33302A",
    "keyboard.kb/signal": "#67AD82",
    "keyboard.kb/surface": "#1D1B16",
    "metrics.addterm/inset": "6",
    "metrics.card/border": "1",
    "metrics.card/radius": "16",
    "metrics.caret/height": "20",
    "metrics.caret/lead": "1",
    "metrics.caret/radius": "1",
    "metrics.caret/width": "2",
    "metrics.gesture/swipe-min": "24",
    "metrics.glyph/hit": "32",
    "metrics.key/gap": "6",
    "metrics.key/height": "42",
    "metrics.key/letter-width-402": "34.8",
    "metrics.key/min-width": "44",
    "metrics.key/pad": "4",
    "metrics.key/radius": "8",
    "metrics.key/return-width-402": "104.4",
    "metrics.key/side-gap-factor": "2",
    "metrics.key/side-width-402": "49.2",
    "metrics.layout/full": "272",
    "metrics.layout/panel": "216",
    "metrics.layout/slim": "60",
    "metrics.margin/side": "3",
    "metrics.margin/vertical": "8",
    "metrics.opacity/dim": "0.8",
    "metrics.opacity/dim-saturation": "0.35",
    "metrics.opacity/disabled": "0.4",
    "metrics.opacity/grain": "0.5",
    "metrics.opacity/home-dim-saturation": "0.45",
    "metrics.opacity/legend": "1",
    "metrics.opacity/legend-muted": "0.5",
    "metrics.opacity/orb-light": "0.3",
    "metrics.opacity/placeholder": "0.4",
    "metrics.opacity/popup-shadow": "0.12",
    "metrics.opacity/press-brighten": "0.15",
    "metrics.opacity/surface-grain": "0.14",
    "metrics.opacity/surface-vignette": "0",
    "metrics.opacity/term-cancel": "0.7",
    "metrics.orb/bar": "40",
    "metrics.orb/dissipate-blur": "0.16",
    "metrics.orb/dissipate-scale": "1.25",
    "metrics.orb/home": "112",
    "metrics.orb/light-reach": "0.9",
    "metrics.orb/light-x": "0.3",
    "metrics.orb/light-y": "0.22",
    "metrics.orb/panel": "96",
    "metrics.panel/spacing": "12",
    "metrics.picker/preview-width": "393",
    "metrics.picker/radius": "10",
    "metrics.picker/scale": "0.42",
    "metrics.popup/extra-width": "18",
    "metrics.popup/height": "56",
    "metrics.popup/offset": "58",
    "metrics.popup/radius": "10",
    "metrics.popup/shadow-radius": "8",
    "metrics.popup/shadow-y": "2",
    "metrics.press/scale": "0.94",
    "metrics.ring/active": "2",
    "metrics.ring/still": "1",
    "metrics.row/gap": "11",
    "metrics.slim/spacing": "8",
    "metrics.surface/vignette-end": "0.75",
    "metrics.surface/vignette-start": "0.3",
    "metrics.term/gap": "8",
    "metrics.term/height": "36",
    "metrics.term/inset": "2",
    "metrics.term/pad": "14",
    "metrics.voicebar/addterm-clearance": "12",
    "metrics.voicebar/height": "44",
    "metrics.voicebar/note-gap": "10",
    "metrics.wave/bar": "2",
    "metrics.wave/bar-height": "24",
    "metrics.wave/bar-width": "240",
    "metrics.wave/gap": "2",
    "metrics.wave/home-height": "44",
    "metrics.wave/home-width": "280",
    "metrics.wave/liquid": "0",
    "metrics.wave/panel-height": "40",
    "metrics.wave/panel-width": "300",
    "metrics.wordmark/height": "22",
    "type.ratio/orb-glyph": "0.34",
    "type.size/body": "16",
    "type.size/caption": "14",
    "type.size/cta": "14",
    "type.size/eyebrow": "12",
    "type.size/glyph": "17",
    "type.size/label": "12",
    "type.size/legend": "16",
    "type.size/letter": "22",
    "type.size/popup": "32",
    "type.size/term": "17",
    "type.size/title": "34",
    "type.tracking/cta": "1.4",
    "type.tracking/eyebrow": "1.2",
    "type.weight/glyph": "medium",
    "type.weight/label": "medium",
    "type.weight/legend": "medium",
    "type.weight/letter": "regular",
    "type.weight/orb-glyph": "semibold",
    "type.weight/popup": "regular",
    "type.weight/term": "regular",
    "motion.caret": "0.5",
    "motion.colour": "0.2",
    "motion.drop": "2.4",
    "motion.drop-hold": "0.9",
    "motion.drop-rise": "0.5",
    "motion.drop-spread": "1",
    "motion.ease/signature": "0.22,1,0.36,1",
    "motion.flip": "0.25",
    "motion.height-change": "0.25",
    "motion.key-press": "0.08",
    "motion.landing": "0.6",
    "motion.mood": "0.8",
    "motion.press": "0.1",
    "motion.ring-period": "1.6",
    "motion.state-fade": "0.5",
    "motion.term-swap": "0.4",
    "motion.wave-fade": "0.7",
    "fonts.body/bold": "UN-11ST-Bold",
    "fonts.body/family": "UN-11 ST",
    "fonts.body/regular": "UN-11ST-Regular",
    "fonts.heading/family": "Oceanic Text",
    "fonts.heading/regular": "OceanicText-Regular",
    "fonts.mono/family": "Modern Gothic Mono",
    "fonts.mono/light": "ModernGothicMono-Light",
    "fonts.mono/medium": "ModernGothicMono-Medium",
    "fonts.mono/regular": "ModernGothicMono-Regular",
    "gradients.orb":
      "#D7D3F4@0 #B0A7E9@0.0673 #67AD82@0.1442 #01762F@0.3029 #3923C7@0.5962 #887BDD@0.75 #D7D3F4@0.8942 #FFFFFF@1 bottom>top",
    "gradients.orb-ring": "#01762F@0 #FFFFFF@1 topLeading>bottomTrailing",
  ]
}
// swiftlint:enable type_body_length
