// Generated by scripts/design-tokens.swift from App/BlurtiOS/Design/tokens.json — do not edit.
// Regenerate with scripts/design-sync.sh; scripts/check.sh fails on drift.
// periphery:ignore:all
// swiftlint:disable file_length
import SwiftUI

// swiftlint:disable type_body_length
/// The design's colours and numbers, from the one source Figma exports
/// (`Design/tokens.json`): what the views draw with, what DESIGN.md's tables
/// say, and what the asset catalog holds, all from the same file. Swift names
/// follow the token names by one rule (`kb/key-modifier` → `kbKeyModifier`),
/// the same rule the Figma build script uses for iOS code syntax.
enum DesignTokens {
  enum Brand {
    /// The iPhone keyboard's dark key.
    nonisolated static let appleDarkKey: Color = Color(hex: 0x6B6B6B)
    /// The iPhone keyboard's dark modifier key.
    nonisolated static let appleDarkModifier: Color = Color(hex: 0x464646)
    /// The iPhone keyboard's dark surface.
    nonisolated static let appleDarkSurface: Color = Color(hex: 0x2B2B2B)
    /// The iPhone keyboard's light modifier key.
    nonisolated static let appleLightModifier: Color = Color(hex: 0xADB3BC)
    /// The iPhone keyboard's light surface.
    nonisolated static let appleLightSurface: Color = Color(hex: 0xD1D5DB)
    nonisolated static let black: Color = Color(hex: 0x000000)
    /// The warm card fill; the paper theme's surface.
    nonisolated static let card: Color = Color(hex: 0xEBE8E8)
    /// The card's hairline; the paper theme's modifier key.
    nonisolated static let cardBorder: Color = Color(hex: 0xDEDBDB)
    /// AssemblyAI's primary violet: the drop, never a key or a surface.
    nonisolated static let cobolt: Color = Color(hex: 0x3923C7)
    /// The design system's UI-and-code green fill (unused on the phone yet).
    nonisolated static let green100: Color = Color(hex: 0xCCE4D5)
    /// The design system's UI-and-code green highlight (unused on the phone yet).
    nonisolated static let green200: Color = Color(hex: 0x99C8AC)
    /// The brand hue lifted for dark chrome: the meter, the ring, the wave on ink.
    nonisolated static let green400: Color = Color(hex: 0x67AD82)
    /// The wordmark green, light chrome (the app's accent in light).
    nonisolated static let green700: Color = Color(hex: 0x01762F)
    /// The pale green the orb lightens into.
    nonisolated static let greenMist: Color = Color(hex: 0xDBF5E6)
    /// The brand ink: the Mac pill's body, the ink theme's surface.
    nonisolated static let ink: Color = Color(hex: 0x1D1B16)
    /// The Mac's dark card border.
    nonisolated static let ink600: Color = Color(hex: 0x3A362F)
    /// An ordinary key on ink, one step up.
    nonisolated static let ink700: Color = Color(hex: 0x33302A)
    /// A modifier key on ink; the Mac's dark card fill.
    nonisolated static let ink800: Color = Color(hex: 0x26231E)
    /// A key on the system's dark keyboard material (measured, iOS 27): the container case.
    nonisolated static let materialDarkKey: Color = Color(hex: 0x575757)
    /// A modifier key on the system's dark material.
    nonisolated static let materialDarkModifier: Color = Color(hex: 0x474747)
    /// The system's dark keyboard material (measured, iOS 27).
    nonisolated static let materialDarkSurface: Color = Color(hex: 0x373737)
    /// The system's light keyboard material (measured, iOS 27): what the gallery stands under a clear surface.
    nonisolated static let materialLightSurface: Color = Color(hex: 0xE2E3E8)
    /// Black-100: the lightest warm grey.
    nonisolated static let neutral300: Color = Color(hex: 0xD2D1D0)
    /// Black-200: mono labels on the dark face.
    nonisolated static let neutral500: Color = Color(hex: 0xA5A4A2)
    /// Black-300: muted text and mono labels on the light face.
    nonisolated static let neutral700: Color = Color(hex: 0x777673)
    /// Black-400: body text on the light face.
    nonisolated static let neutral900: Color = Color(hex: 0x4A4945)
    /// The error word and ring, cancel, the Full Access note; never a red body.
    nonisolated static let orange: Color = Color(hex: 0xE67F36)
    /// Neutral-100: the light face's surface.
    nonisolated static let paper200: Color = Color(hex: 0xECEBE5)
    /// Neutral-200: a modifier key on the light face.
    nonisolated static let paper300: Color = Color(hex: 0xDAD7CB)
    /// Neutral-300: hairlines and field borders on the light face.
    nonisolated static let paper400: Color = Color(hex: 0xC7C3B2)
    /// The design system's page: the app's light ground.
    nonisolated static let paperPage: Color = Color(hex: 0xFDFCF8)
    /// The warm off-white one step in: light cards, dark legends.
    nonisolated static let paperTint: Color = Color(hex: 0xF5F3EB)
    /// The orb gradient's upper violet stop.
    nonisolated static let violetIris: Color = Color(hex: 0x887BDD)
    /// The orb's lightest violet: its top and the gradient's ends.
    nonisolated static let violetLavender: Color = Color(hex: 0xD7D3F4)
    /// The orb's mid violet: the drop's halo.
    nonisolated static let violetPeriwinkle: Color = Color(hex: 0xB0A7E9)
    /// Key legends on ink: warm white on warm ink.
    nonisolated static let warmWhite: Color = Color(hex: 0xF2EEE6)
    nonisolated static let white: Color = Color(hex: 0xFFFFFF)
  }

  enum Themes {
    /// `brand.material/dark-key`.
    nonisolated static let darkContainerKey: Color = Brand.materialDarkKey
    /// `brand.material/dark-modifier`.
    nonisolated static let darkContainerKeyModifier: Color = Brand.materialDarkModifier
    /// `brand.ink/700`.
    nonisolated static let darkField: Color = Brand.ink700
    /// `brand.ink/600`.
    nonisolated static let darkFieldBorder: Color = Brand.ink600
    /// `brand.ink/700`.
    nonisolated static let darkKey: Color = Brand.ink700
    /// `brand.ink/800`.
    nonisolated static let darkKeyModifier: Color = Brand.ink800
    /// `brand.paper/tint`.
    nonisolated static let darkLegend: Color = Brand.paperTint
    /// `brand.neutral/500`.
    nonisolated static let darkLegendSecondary: Color = Brand.neutral500
    /// `brand.material/dark-surface`.
    nonisolated static let darkMaterial: Color = Brand.materialDarkSurface
    /// `brand.orange`.
    nonisolated static let darkNotice: Color = Brand.orange
    /// `brand.ink/700`.
    nonisolated static let darkPopup: Color = Brand.ink700
    /// `brand.green/400`.
    nonisolated static let darkSignal: Color = Brand.green400
    /// `brand.ink`.
    nonisolated static let darkSurface: Color = Brand.ink
    /// `brand.white`.
    nonisolated static let lightContainerKey: Color = Brand.white
    /// `brand.paper/300`.
    nonisolated static let lightContainerKeyModifier: Color = Brand.paper300
    /// `brand.white`.
    nonisolated static let lightField: Color = Brand.white
    /// `brand.paper/400`.
    nonisolated static let lightFieldBorder: Color = Brand.paper400
    /// `brand.white`.
    nonisolated static let lightKey: Color = Brand.white
    /// `brand.paper/300`.
    nonisolated static let lightKeyModifier: Color = Brand.paper300
    /// `brand.ink`.
    nonisolated static let lightLegend: Color = Brand.ink
    /// `brand.neutral/700`.
    nonisolated static let lightLegendSecondary: Color = Brand.neutral700
    /// `brand.material/light-surface`.
    nonisolated static let lightMaterial: Color = Brand.materialLightSurface
    /// `brand.orange`.
    nonisolated static let lightNotice: Color = Brand.orange
    /// `brand.white`.
    nonisolated static let lightPopup: Color = Brand.white
    /// `brand.green/700`.
    nonisolated static let lightSignal: Color = Brand.green700
    /// `brand.paper/200`.
    nonisolated static let lightSurface: Color = Brand.paper200
  }

  enum Keyboard {
    /// The catalog's AccentColor in dark.
    nonisolated static let appAccentDark: Color = Brand.green400
    /// The catalog's AccentColor in light.
    nonisolated static let appAccentLight: Color = Brand.green700
    /// The catalog's CardBorder in dark.
    nonisolated static let appCardBorderDark: Color = Brand.ink600
    /// The catalog's CardBorder in light.
    nonisolated static let appCardBorderLight: Color = Brand.paper400
    /// The catalog's CardFill in dark.
    nonisolated static let appCardFillDark: Color = Brand.ink800
    /// The catalog's CardFill in light.
    nonisolated static let appCardFillLight: Color = Brand.paperTint
    /// The catalog's CTA in dark: the site's button green.
    nonisolated static let appCtaDark: Color = Brand.green400
    /// The catalog's CTA in light: the one green button.
    nonisolated static let appCtaLight: Color = Brand.green700
    /// The catalog's CTAText in dark: ink on green, as the site.
    nonisolated static let appCtaTextDark: Color = Brand.ink
    /// The catalog's CTAText in light.
    nonisolated static let appCtaTextLight: Color = Brand.white
    /// The catalog's Muted in dark.
    nonisolated static let appMutedDark: Color = Brand.neutral500
    /// The catalog's Muted in light: eyebrows, captions, secondary text.
    nonisolated static let appMutedLight: Color = Brand.neutral700
    /// The catalog's Page in dark: ink, the website's ground.
    nonisolated static let appPageDark: Color = Brand.ink
    /// The catalog's Page in light: the design system's page.
    nonisolated static let appPageLight: Color = Brand.paperPage
    /// The catalog's Text in dark.
    nonisolated static let appTextDark: Color = Brand.paperTint
    /// The catalog's Text in light.
    nonisolated static let appTextLight: Color = Brand.ink
    /// The panel's cancel ×.
    nonisolated static let kbCancel: Color = Brand.orange
    /// The key-term field.
    nonisolated static let kbField: Color = Themes.darkField
    /// The field's hairline.
    nonisolated static let kbFieldBorder: Color = Themes.darkFieldBorder
    /// The one line of words the keyboard ever shows.
    nonisolated static let kbFullAccessNote: Color = Brand.orange
    /// An ordinary key.
    nonisolated static let kbKey: Color = Themes.darkKey
    /// Shift, delete, globe, return, 123, cancel.
    nonisolated static let kbKeyModifier: Color = Themes.darkKeyModifier
    /// Key legends and bare glyphs.
    nonisolated static let kbLegend: Color = Themes.darkLegend
    /// The mono word labels (123, ABC, return, space) and the + at rest.
    nonisolated static let kbLegendSecondary: Color = Themes.darkLegendSecondary
    /// The solid ring and glyph for an error.
    nonisolated static let kbNoticeError: Color = Brand.orange
    /// The letter pop-up.
    nonisolated static let kbPopup: Color = Themes.darkPopup
    /// The wave, the caret, the saved check.
    nonisolated static let kbSignal: Color = Themes.darkSignal
    /// The design face's surface (Figma binds to kb/*; Swift reads the palette).
    nonisolated static let kbSurface: Color = Themes.darkSurface
  }

  enum Metrics {
    /// Between the chip's glyph and the word.
    nonisolated static let addtermChipGap: CGFloat = 6
    /// The most the chip may take in the panel's corner, clear of the cancel ×.
    nonisolated static let addtermChipMaxWidth: CGFloat = 240
    /// The room the voice bar keeps for the chip; the element gives way beyond it.
    nonisolated static let addtermChipMinWidth: CGFloat = 96
    /// The selected-word chip's side padding.
    nonisolated static let addtermChipPad: CGFloat = 10
    /// The + from the panel's corner.
    nonisolated static let addtermInset: CGFloat = 6
    /// The brand's button.
    nonisolated static let appButtonHeight: CGFloat = 40
    /// Its side padding.
    nonisolated static let appButtonPad: CGFloat = 12
    /// Inside a card.
    nonisolated static let appCardPad: CGFloat = 16
    /// Between chips.
    nonisolated static let appChipGap: CGFloat = 8
    /// A style chip's side padding.
    nonisolated static let appChipPadX: CGFloat = 12
    /// And its top and bottom.
    nonisolated static let appChipPadY: CGFloat = 8
    /// The home header: wordmark and gear.
    nonisolated static let appHeaderHeight: CGFloat = 44
    /// Between the hero's pieces.
    nonisolated static let appHeroGap: CGFloat = 14
    /// Inside the hero card.
    nonisolated static let appHeroPad: CGFloat = 20
    /// The header's gear, the copy glyph.
    nonisolated static let appIcon: CGFloat = 20
    /// Between lines of one thought.
    nonisolated static let appLineGap: CGFloat = 6
    /// The screens' side padding.
    nonisolated static let appPagePad: CGFloat = 20
    /// Between the theme card's two faces.
    nonisolated static let appPreviewGap: CGFloat = 8
    /// Between the home screen's sections.
    nonisolated static let appSectionGap: CGFloat = 24
    /// The setup steps' mono numerals.
    nonisolated static let appSetupNumberWidth: CGFloat = 24
    /// Between a section's eyebrow and its content, and between cards.
    nonisolated static let appStackGap: CGFloat = 12
    /// The card's hairline.
    nonisolated static let cardBorder: CGFloat = 1
    /// The app's cards (radius/card).
    nonisolated static let cardRadius: CGFloat = 12
    nonisolated static let caretHeight: CGFloat = 20
    /// The caret's gap from the text.
    nonisolated static let caretLead: CGFloat = 1
    nonisolated static let caretRadius: CGFloat = 1
    nonisolated static let caretWidth: CGFloat = 2
    /// The +, × and ✓ touch targets.
    nonisolated static let glyphHit: CGFloat = 32
    nonisolated static let grilleBarHeight: CGFloat = 28
    /// The grille in the voice bar.
    nonisolated static let grilleBarWidth: CGFloat = 64
    /// A dot's diameter.
    nonisolated static let grilleDot: CGFloat = 2
    /// The cross glint's vertical arm, as a fraction of the grille's height.
    nonisolated static let grilleGlintArm: CGFloat = 1.6
    /// The glint's arms.
    nonisolated static let grilleGlintWidth: CGFloat = 1
    nonisolated static let grilleHomeHeight: CGFloat = 108
    /// The grille on the home screen.
    nonisolated static let grilleHomeWidth: CGFloat = 240
    nonisolated static let grillePanelHeight: CGFloat = 72
    /// The grille in the panel.
    nonisolated static let grillePanelWidth: CGFloat = 160
    /// The dot lattice: one dot every.
    nonisolated static let grillePitch: CGFloat = 4
    /// The sheen's band, as a fraction of the width.
    nonisolated static let grilleSheenWidth: CGFloat = 0.35
    /// 123 and the globe at 402 pt: the iPhone's.
    nonisolated static let keyAbcWidth402: CGFloat = 43.333
    /// Between keys, the iPhone's.
    nonisolated static let keyGap: CGFloat = 6
    /// Every key: the iPhone's cap height (apple-geometry.json).
    nonisolated static let keyHeight: CGFloat = 43
    /// A letter key at 402 pt: (width − 2 × margin/side − 9 × key/gap) / 10.
    nonisolated static let keyLetterWidth402: CGFloat = 33.5
    /// A key that isn't given a width: the iPhone's 123 key at 402 pt.
    nonisolated static let keyMinWidth: CGFloat = 43.333
    /// A legend's side padding on a min-width key.
    nonisolated static let keyPad: CGFloat = 4
    /// Flat keys, one colour at this corner: the iPhone's (fitted 8.17).
    nonisolated static let keyRadius: CGFloat = 8
    /// The width the @402 tokens were measured at (iPhone 18 Pro); widths scale from it.
    nonisolated static let keyReferenceWidth: CGFloat = 402
    /// Return at 402 pt: two 123 keys and a gap.
    nonisolated static let keyReturnWidth402: CGFloat = 92.667
    /// Shift and delete stand this far from the letters: the iPhone's.
    nonisolated static let keySideGap: CGFloat = 13.667
    /// Shift and delete at 402 pt: what seven letters and the side gaps leave, halved (measured 45.5).
    nonisolated static let keySideWidth402: CGFloat = 45.583
    /// Space at 402 pt beside 123, the globe and return: what is left (measured 191.333).
    nonisolated static let keySpaceWidth402: CGFloat = 191.667
    /// Margin/vertical + voicebar/height + 4 × key/height + 3 × row/gap + margin/bottom-keys.
    nonisolated static let layoutFull: CGFloat = 270
    /// Chosen: room for the 96 orb over one key row.
    nonisolated static let layoutPanel: CGFloat = 216
    /// 2 × margin/vertical + voicebar/height.
    nonisolated static let layoutSlim: CGFloat = 60
    /// Under a bottom row of keys (the full keyboard, the panel): the iPhone's.
    nonisolated static let marginBottomKeys: CGFloat = 13
    /// At the keyboard's sides: the iPhone's cap margin, (402 − 10 letters − 9 gaps) / 2.
    nonisolated static let marginSide: CGFloat = 6.5
    /// The keyboard's top, and the slim bar's bottom.
    nonisolated static let marginVertical: CGFloat = 8
    /// The + without Full Access.
    nonisolated static let opacityDisabled: CGFloat = 0.4
    /// The cross glint when the words land.
    nonisolated static let opacityGlint: CGFloat = 0.95
    /// Film grain over the dark face: matte, the brand's texture.
    nonisolated static let opacityGrainDark: CGFloat = 0.14
    /// Film grain over the light face: paper, lighter.
    nonisolated static let opacityGrainLight: CGFloat = 0.08
    /// The dots at rest, over the key colour.
    nonisolated static let opacityGrilleRest: CGFloat = 0.55
    nonisolated static let opacityHairline: CGFloat = 0.5
    /// Key legends over the cap; below 1 they sit back.
    nonisolated static let opacityLegend: CGFloat = 1
    /// The + at rest.
    nonisolated static let opacityLegendMuted: CGFloat = 0.5
    /// The element when Blurt isn't ready — dim and still, but there: a tap opens the app.
    nonisolated static let opacityOff: CGFloat = 0.6
    /// The field's placeholder.
    nonisolated static let opacityPlaceholder: CGFloat = 0.4
    nonisolated static let opacityPopupShadow: CGFloat = 0.12
    /// A key lightens this much while pressed.
    nonisolated static let opacityPressBrighten: CGFloat = 0.15
    /// A brand button while pressed: a colour change, no lift.
    nonisolated static let opacityPressed: CGFloat = 0.85
    /// The light passing over the element at rest: chrome catching light.
    nonisolated static let opacitySheen: CGFloat = 0.22
    /// A soft darkening toward the surface's edges; 0 is none.
    nonisolated static let opacitySurfaceVignette: CGFloat = 0
    /// The field's ×.
    nonisolated static let opacityTermCancel: CGFloat = 0.7
    /// Between the panel's orb and its key row.
    nonisolated static let panelSpacing: CGFloat = 12
    /// The theme card draws the keyboard at this width.
    nonisolated static let pickerPreviewWidth: CGFloat = 393
    /// The theme card's preview corners.
    nonisolated static let pickerRadius: CGFloat = 10
    /// Then scales it to fit two across.
    nonisolated static let pickerScale: CGFloat = 0.42
    /// The letter pop-up is the key width plus this.
    nonisolated static let popupExtraWidth: CGFloat = 18
    nonisolated static let popupHeight: CGFloat = 56
    /// The pop-up sits this far above the key.
    nonisolated static let popupOffset: CGFloat = 58
    nonisolated static let popupRadius: CGFloat = 10
    /// The one thing that floats.
    nonisolated static let popupShadowRadius: CGFloat = 8
    nonisolated static let popupShadowY: CGFloat = 2
    /// The brand's buttons and the grille: rectangular, never a pill.
    nonisolated static let radiusButton: CGFloat = 4
    /// The brand's cards.
    nonisolated static let radiusCard: CGFloat = 12
    /// The brand's featured cards.
    nonisolated static let radiusHero: CGFloat = 16
    /// The brand's inputs: the key-term field.
    nonisolated static let radiusInput: CGFloat = 8
    nonisolated static let ribsRestHeight: CGFloat = 16
    /// The ribs asleep: the wave's own bars at rest.
    nonisolated static let ribsRestWidth: CGFloat = 40
    /// Between rows, the iPhone's.
    nonisolated static let rowGap: CGFloat = 11
    /// Between the slim bar's keys.
    nonisolated static let slimSpacing: CGFloat = 8
    /// The landing flash's vertical arm, as a fraction of the box's height.
    nonisolated static let streakArm: CGFloat = 1.4
    /// The light streak while recording.
    nonisolated static let streakHeight: CGFloat = 2
    /// The hairline at rest.
    nonisolated static let streakLine: CGFloat = 1
    /// The bright point at the centre.
    nonisolated static let streakPoint: CGFloat = 4
    /// 1 paints the face's surface under the keys; 0 leaves it clear, so the host's own keyboard material (iOS 26's rounded container, which insets a third-party keyboard and cannot be painted over) is the surface, seamlessly, and the keys take the container colours.
    nonisolated static let surfacePaint: CGFloat = 0
    /// Where it is full.
    nonisolated static let surfaceVignetteEnd: CGFloat = 0.75
    /// Where the vignette begins, as a fraction of the keyboard's width.
    nonisolated static let surfaceVignetteStart: CGFloat = 0.3
    /// The field's hairline.
    nonisolated static let termBorder: CGFloat = 1
    /// × · field · ✓.
    nonisolated static let termGap: CGFloat = 8
    /// The key-term field's capsule.
    nonisolated static let termHeight: CGFloat = 36
    /// The field row's side inset.
    nonisolated static let termInset: CGFloat = 2
    /// The field's side padding.
    nonisolated static let termPad: CGFloat = 14
    /// The key-term field: the brand's input corners (radius/input).
    nonisolated static let termRadius: CGFloat = 8
    nonisolated static let voiceBarHeight: CGFloat = 32
    /// The voice element's box in the voice bar — the most it takes (the ribs awake, the streak); the + sits beside what shows.
    nonisolated static let voiceBarWidth: CGFloat = 160
    nonisolated static let voiceHomeHeight: CGFloat = 112
    /// The box on the home screen.
    nonisolated static let voiceHomeWidth: CGFloat = 280
    nonisolated static let voicePanelHeight: CGFloat = 88
    /// The box in the panel.
    nonisolated static let voicePanelWidth: CGFloat = 300
    /// The element while pressed.
    nonisolated static let voicePressScale: CGFloat = 0.94
    /// Between the element and the +.
    nonisolated static let voicebarAddtermClearance: CGFloat = 12
    /// The voice row, where the system puts its suggestion bar.
    nonisolated static let voicebarHeight: CGFloat = 44
    /// Between the orb and the Full Access note.
    nonisolated static let voicebarNoteGap: CGFloat = 10
    /// A wave bar's width.
    nonisolated static let waveBar: CGFloat = 2
    nonisolated static let waveBarHeight: CGFloat = 24
    /// Between wave bars.
    nonisolated static let waveGap: CGFloat = 2
    nonisolated static let waveHomeHeight: CGFloat = 44
    nonisolated static let wavePanelHeight: CGFloat = 40
    nonisolated static let wordmarkHeight: CGFloat = 22
  }

  enum Typography {
    /// The clipboard and exclamation glyphs, as a fraction of the voice element's height.
    nonisolated static let ratioVoiceGlyph: CGFloat = 0.34
    /// The app's body text.
    nonisolated static let sizeBody: CGFloat = 16
    /// The app's small text.
    nonisolated static let sizeCaption: CGFloat = 14
    /// A mono button label in the app (E2).
    nonisolated static let sizeCta: CGFloat = 14
    /// A mono eyebrow in the app (E1).
    nonisolated static let sizeEyebrow: CGFloat = 12
    /// The +, × and ✓.
    nonisolated static let sizeGlyph: CGFloat = 17
    /// The mono word labels on keys: 123, ABC, #+=, space, the return label.
    nonisolated static let sizeLabel: CGFloat = 12
    /// Every other key.
    nonisolated static let sizeLegend: CGFloat = 16
    /// Letter keys: the iPhone's (estimated from the l glyph, apple-geometry.json).
    nonisolated static let sizeLetter: CGFloat = 24
    /// The letter pop-up.
    nonisolated static let sizePopup: CGFloat = 32
    /// The key-term field.
    nonisolated static let sizeTerm: CGFloat = 17
    /// The app's serif headline.
    nonisolated static let sizeTitle: CGFloat = 34
    /// Uppercase mono at 14: the brand's E2 tracking.
    nonisolated static let trackingCta: CGFloat = 1.4
    /// Uppercase mono at 12: the brand's E1 tracking.
    nonisolated static let trackingEyebrow: CGFloat = 1.2
    nonisolated static let weightGlyph: Font.Weight = .medium
    nonisolated static let weightLabel: Font.Weight = .medium
    nonisolated static let weightLegend: Font.Weight = .medium
    nonisolated static let weightLetter: Font.Weight = .regular
    nonisolated static let weightPopup: Font.Weight = .regular
    nonisolated static let weightTerm: Font.Weight = .regular
    nonisolated static let weightVoiceGlyph: Font.Weight = .semibold
  }

  enum Motion {
    /// The caret's blink.
    nonisolated static let caret: Double = 0.5
    /// Holding the chip opens the field instead of adding.
    nonisolated static let chipHold: Double = 0.4
    /// A colour or fill changing state: the brand's transition.
    nonisolated static let colour: Double = 0.2
    /// The house curve for everything that moves; nothing springs.
    nonisolated static let easeSignature: UnitCurve = UnitCurve.bezier(
      startControlPoint: UnitPoint(x: 0.22, y: 1), endControlPoint: UnitPoint(x: 0.36, y: 1))
    /// The panel's carousel.
    nonisolated static let flip: Double = 0.25
    /// A facet's flash while recording.
    nonisolated static let glintLife: Double = 0.5
    /// The keyboard resizing.
    nonisolated static let heightChange: Double = 0.25
    /// A key lighting.
    nonisolated static let keyPress: Double = 0.08
    /// The glint when the words land.
    nonisolated static let landing: Double = 0.6
    /// The orb's press; the one thing that answers at once.
    nonisolated static let press: Double = 0.1
    /// One turn of the ring, the Mac's cadence.
    nonisolated static let ringPeriod: Double = 1.6
    /// One pass of the light over the element at rest.
    nonisolated static let sheen: Double = 4
    /// And while something is happening: the ring's cadence.
    nonisolated static let sheenWorking: Double = 1.6
    /// Every other change on the key: the ring, a glyph, the dimming.
    nonisolated static let stateFade: Double = 0.5
    /// The voice bar becoming the field.
    nonisolated static let termSwap: Double = 0.4
    /// The orb and the wave crossing, either way.
    nonisolated static let waveFade: Double = 0.7
  }

  enum Fonts {
    nonisolated static let bodyBold: String = "UN-11ST-Bold"
    /// The app's body text.
    nonisolated static let bodyFamily: String = "UN-11 ST"
    nonisolated static let bodyRegular: String = "UN-11ST-Regular"
    /// The app's serif headlines, sentence case, tight.
    nonisolated static let headingFamily: String = "Oceanic Text"
    nonisolated static let headingRegular: String = "OceanicText-Regular"
    /// Eyebrows, CTAs, the keyboard's word labels.
    nonisolated static let monoFamily: String = "Modern Gothic Mono"
    nonisolated static let monoLight: String = "ModernGothicMono-Light"
    nonisolated static let monoMedium: String = "ModernGothicMono-Medium"
    nonisolated static let monoRegular: String = "ModernGothicMono-Regular"
  }

  enum Gradients {
  }

  /// Every token as `group.name: value`, the way tokens.json renders it, so a
  /// test can pin the compiled values to the file (`DesignTokensTests`).
  nonisolated static let manifest: [String: String] = [
    "brand.apple/dark-key": "#6B6B6B",
    "brand.apple/dark-modifier": "#464646",
    "brand.apple/dark-surface": "#2B2B2B",
    "brand.apple/light-modifier": "#ADB3BC",
    "brand.apple/light-surface": "#D1D5DB",
    "brand.black": "#000000",
    "brand.card": "#EBE8E8",
    "brand.card-border": "#DEDBDB",
    "brand.cobolt": "#3923C7",
    "brand.green/100": "#CCE4D5",
    "brand.green/200": "#99C8AC",
    "brand.green/400": "#67AD82",
    "brand.green/700": "#01762F",
    "brand.green/mist": "#DBF5E6",
    "brand.ink": "#1D1B16",
    "brand.ink/600": "#3A362F",
    "brand.ink/700": "#33302A",
    "brand.ink/800": "#26231E",
    "brand.material/dark-key": "#575757",
    "brand.material/dark-modifier": "#474747",
    "brand.material/dark-surface": "#373737",
    "brand.material/light-surface": "#E2E3E8",
    "brand.neutral/300": "#D2D1D0",
    "brand.neutral/500": "#A5A4A2",
    "brand.neutral/700": "#777673",
    "brand.neutral/900": "#4A4945",
    "brand.orange": "#E67F36",
    "brand.paper/200": "#ECEBE5",
    "brand.paper/300": "#DAD7CB",
    "brand.paper/400": "#C7C3B2",
    "brand.paper/page": "#FDFCF8",
    "brand.paper/tint": "#F5F3EB",
    "brand.violet/iris": "#887BDD",
    "brand.violet/lavender": "#D7D3F4",
    "brand.violet/periwinkle": "#B0A7E9",
    "brand.warm-white": "#F2EEE6",
    "brand.white": "#FFFFFF",
    "themes.dark/container-key": "#575757",
    "themes.dark/container-key-modifier": "#474747",
    "themes.dark/field": "#33302A",
    "themes.dark/field-border": "#3A362F",
    "themes.dark/key": "#33302A",
    "themes.dark/key-modifier": "#26231E",
    "themes.dark/legend": "#F5F3EB",
    "themes.dark/legend-secondary": "#A5A4A2",
    "themes.dark/material": "#373737",
    "themes.dark/notice": "#E67F36",
    "themes.dark/popup": "#33302A",
    "themes.dark/signal": "#67AD82",
    "themes.dark/surface": "#1D1B16",
    "themes.light/container-key": "#FFFFFF",
    "themes.light/container-key-modifier": "#DAD7CB",
    "themes.light/field": "#FFFFFF",
    "themes.light/field-border": "#C7C3B2",
    "themes.light/key": "#FFFFFF",
    "themes.light/key-modifier": "#DAD7CB",
    "themes.light/legend": "#1D1B16",
    "themes.light/legend-secondary": "#777673",
    "themes.light/material": "#E2E3E8",
    "themes.light/notice": "#E67F36",
    "themes.light/popup": "#FFFFFF",
    "themes.light/signal": "#01762F",
    "themes.light/surface": "#ECEBE5",
    "keyboard.app/accent-dark": "#67AD82",
    "keyboard.app/accent-light": "#01762F",
    "keyboard.app/card-border-dark": "#3A362F",
    "keyboard.app/card-border-light": "#C7C3B2",
    "keyboard.app/card-fill-dark": "#26231E",
    "keyboard.app/card-fill-light": "#F5F3EB",
    "keyboard.app/cta-dark": "#67AD82",
    "keyboard.app/cta-light": "#01762F",
    "keyboard.app/cta-text-dark": "#1D1B16",
    "keyboard.app/cta-text-light": "#FFFFFF",
    "keyboard.app/muted-dark": "#A5A4A2",
    "keyboard.app/muted-light": "#777673",
    "keyboard.app/page-dark": "#1D1B16",
    "keyboard.app/page-light": "#FDFCF8",
    "keyboard.app/text-dark": "#F5F3EB",
    "keyboard.app/text-light": "#1D1B16",
    "keyboard.kb/cancel": "#E67F36",
    "keyboard.kb/field": "#33302A",
    "keyboard.kb/field-border": "#3A362F",
    "keyboard.kb/full-access-note": "#E67F36",
    "keyboard.kb/key": "#33302A",
    "keyboard.kb/key-modifier": "#26231E",
    "keyboard.kb/legend": "#F5F3EB",
    "keyboard.kb/legend-secondary": "#A5A4A2",
    "keyboard.kb/notice-error": "#E67F36",
    "keyboard.kb/popup": "#33302A",
    "keyboard.kb/signal": "#67AD82",
    "keyboard.kb/surface": "#1D1B16",
    "metrics.addterm/chip-gap": "6",
    "metrics.addterm/chip-max-width": "240",
    "metrics.addterm/chip-min-width": "96",
    "metrics.addterm/chip-pad": "10",
    "metrics.addterm/inset": "6",
    "metrics.app/button-height": "40",
    "metrics.app/button-pad": "12",
    "metrics.app/card-pad": "16",
    "metrics.app/chip-gap": "8",
    "metrics.app/chip-pad-x": "12",
    "metrics.app/chip-pad-y": "8",
    "metrics.app/header-height": "44",
    "metrics.app/hero-gap": "14",
    "metrics.app/hero-pad": "20",
    "metrics.app/icon": "20",
    "metrics.app/line-gap": "6",
    "metrics.app/page-pad": "20",
    "metrics.app/preview-gap": "8",
    "metrics.app/section-gap": "24",
    "metrics.app/setup-number-width": "24",
    "metrics.app/stack-gap": "12",
    "metrics.card/border": "1",
    "metrics.card/radius": "12",
    "metrics.caret/height": "20",
    "metrics.caret/lead": "1",
    "metrics.caret/radius": "1",
    "metrics.caret/width": "2",
    "metrics.glyph/hit": "32",
    "metrics.grille/bar-height": "28",
    "metrics.grille/bar-width": "64",
    "metrics.grille/dot": "2",
    "metrics.grille/glint-arm": "1.6",
    "metrics.grille/glint-width": "1",
    "metrics.grille/home-height": "108",
    "metrics.grille/home-width": "240",
    "metrics.grille/panel-height": "72",
    "metrics.grille/panel-width": "160",
    "metrics.grille/pitch": "4",
    "metrics.grille/sheen-width": "0.35",
    "metrics.key/abc-width-402": "43.333",
    "metrics.key/gap": "6",
    "metrics.key/height": "43",
    "metrics.key/letter-width-402": "33.5",
    "metrics.key/min-width": "43.333",
    "metrics.key/pad": "4",
    "metrics.key/radius": "8",
    "metrics.key/reference-width": "402",
    "metrics.key/return-width-402": "92.667",
    "metrics.key/side-gap": "13.667",
    "metrics.key/side-width-402": "45.583",
    "metrics.key/space-width-402": "191.667",
    "metrics.layout/full": "270",
    "metrics.layout/panel": "216",
    "metrics.layout/slim": "60",
    "metrics.margin/bottom-keys": "13",
    "metrics.margin/side": "6.5",
    "metrics.margin/vertical": "8",
    "metrics.opacity/disabled": "0.4",
    "metrics.opacity/glint": "0.95",
    "metrics.opacity/grain-dark": "0.14",
    "metrics.opacity/grain-light": "0.08",
    "metrics.opacity/grille-rest": "0.55",
    "metrics.opacity/hairline": "0.5",
    "metrics.opacity/legend": "1",
    "metrics.opacity/legend-muted": "0.5",
    "metrics.opacity/off": "0.6",
    "metrics.opacity/placeholder": "0.4",
    "metrics.opacity/popup-shadow": "0.12",
    "metrics.opacity/press-brighten": "0.15",
    "metrics.opacity/pressed": "0.85",
    "metrics.opacity/sheen": "0.22",
    "metrics.opacity/surface-vignette": "0",
    "metrics.opacity/term-cancel": "0.7",
    "metrics.panel/spacing": "12",
    "metrics.picker/preview-width": "393",
    "metrics.picker/radius": "10",
    "metrics.picker/scale": "0.42",
    "metrics.popup/extra-width": "18",
    "metrics.popup/height": "56",
    "metrics.popup/offset": "58",
    "metrics.popup/radius": "10",
    "metrics.popup/shadow-radius": "8",
    "metrics.popup/shadow-y": "2",
    "metrics.radius/button": "4",
    "metrics.radius/card": "12",
    "metrics.radius/hero": "16",
    "metrics.radius/input": "8",
    "metrics.ribs/rest-height": "16",
    "metrics.ribs/rest-width": "40",
    "metrics.row/gap": "11",
    "metrics.slim/spacing": "8",
    "metrics.streak/arm": "1.4",
    "metrics.streak/height": "2",
    "metrics.streak/line": "1",
    "metrics.streak/point": "4",
    "metrics.surface/paint": "0",
    "metrics.surface/vignette-end": "0.75",
    "metrics.surface/vignette-start": "0.3",
    "metrics.term/border": "1",
    "metrics.term/gap": "8",
    "metrics.term/height": "36",
    "metrics.term/inset": "2",
    "metrics.term/pad": "14",
    "metrics.term/radius": "8",
    "metrics.voice/bar-height": "32",
    "metrics.voice/bar-width": "160",
    "metrics.voice/home-height": "112",
    "metrics.voice/home-width": "280",
    "metrics.voice/panel-height": "88",
    "metrics.voice/panel-width": "300",
    "metrics.voice/press-scale": "0.94",
    "metrics.voicebar/addterm-clearance": "12",
    "metrics.voicebar/height": "44",
    "metrics.voicebar/note-gap": "10",
    "metrics.wave/bar": "2",
    "metrics.wave/bar-height": "24",
    "metrics.wave/gap": "2",
    "metrics.wave/home-height": "44",
    "metrics.wave/panel-height": "40",
    "metrics.wordmark/height": "22",
    "type.ratio/voice-glyph": "0.34",
    "type.size/body": "16",
    "type.size/caption": "14",
    "type.size/cta": "14",
    "type.size/eyebrow": "12",
    "type.size/glyph": "17",
    "type.size/label": "12",
    "type.size/legend": "16",
    "type.size/letter": "24",
    "type.size/popup": "32",
    "type.size/term": "17",
    "type.size/title": "34",
    "type.tracking/cta": "1.4",
    "type.tracking/eyebrow": "1.2",
    "type.weight/glyph": "medium",
    "type.weight/label": "medium",
    "type.weight/legend": "medium",
    "type.weight/letter": "regular",
    "type.weight/popup": "regular",
    "type.weight/term": "regular",
    "type.weight/voice-glyph": "semibold",
    "motion.caret": "0.5",
    "motion.chip-hold": "0.4",
    "motion.colour": "0.2",
    "motion.ease/signature": "0.22,1,0.36,1",
    "motion.flip": "0.25",
    "motion.glint-life": "0.5",
    "motion.height-change": "0.25",
    "motion.key-press": "0.08",
    "motion.landing": "0.6",
    "motion.press": "0.1",
    "motion.ring-period": "1.6",
    "motion.sheen": "4",
    "motion.sheen-working": "1.6",
    "motion.state-fade": "0.5",
    "motion.term-swap": "0.4",
    "motion.wave-fade": "0.7",
    "fonts.body/bold": "UN-11ST-Bold",
    "fonts.body/family": "UN-11 ST",
    "fonts.body/regular": "UN-11ST-Regular",
    "fonts.heading/family": "Oceanic Text",
    "fonts.heading/regular": "OceanicText-Regular",
    "fonts.mono/family": "Modern Gothic Mono",
    "fonts.mono/light": "ModernGothicMono-Light",
    "fonts.mono/medium": "ModernGothicMono-Medium",
    "fonts.mono/regular": "ModernGothicMono-Regular",
  ]
}
// swiftlint:enable type_body_length
